---
title: "Sulcal Depth stats"
output:
  html_document:
    keep_md: TRUE 
  
---

### Loading in Subject Lists and Demographics
```{r}
demographics <- read.csv("/projects/dmiranda/NEWallSubjects_completeData3_DM_not_sexmatched.csv",header = T)
ASDD_sub <- read.csv("/projects/dmiranda/sulc/subjects/subjects_ASDD.csv",header = FALSE)
COBRE_sub <- read.csv("/projects/dmiranda/sulc/subjects/subjects_COBRE.csv",header = FALSE)
DTI3T_sub <- read.csv("/projects/dmiranda/sulc/subjects/subjects_DTI.csv",header = FALSE)
PNSC_sub <- read.csv("/projects/dmiranda/sulc/subjects/subjects_PNS.csv",header = FALSE)
RTMSWM_sub <- read.csv("/projects/dmiranda/sulc/subjects/subjects_RTMS.csv",header = FALSE)
SPINS_sub <- read.csv("/projects/dmiranda/sulc/subjects/subjects_SPINS.csv",header = FALSE)
ZHH_sub <- read.csv("/projects/dmiranda/sulc/subjects/subjects_ZHH.csv",header = FALSE)
distance <- read.csv("/projects/dmiranda/SZ_pint_concat_20171218.csv")
```

### Creating ivertex dataframe
```{r}
i_vertex <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",ASDD_sub[1,1],"/",ASDD_sub[1,1],".meants.csv",sep = ""))
i_vertex <- read.csv(i_vertex, header = F)
colnames(i_vertex)<- c("ivertex_sulc")
i_vertex$subid <- ASDD_sub[1,1]
i_vertex$roiidx <- 1:nrow(data.frame(i_vertex))
#adding ASDD to dataframe(ivertex)
for(num in 2:15) {
  newpath <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",ASDD_sub[num,1],"/",ASDD_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("ivertex_sulc")
  newdata$subid <- ASDD_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  i_vertex <- rbind(i_vertex, newdata, deparse.level = 1)
}
#adding COBRE to dataframe(ivertex)
for(num in 1:112) {
  newpath <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",COBRE_sub[num,1],"/",COBRE_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("ivertex_sulc")
  newdata$subid <- COBRE_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  i_vertex <- rbind(i_vertex, newdata, deparse.level = 1)
}
#adding DTI3T to dataframe(ivertex)
for(num in 1:43) {
  newpath <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",DTI3T_sub[num,1],"/",DTI3T_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("ivertex_sulc")
  newdata$subid <- DTI3T_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  i_vertex <- rbind(i_vertex, newdata, deparse.level = 1)
}
#adding PNSC to dataframe(ivertex)
for(num in 1:7) {
  newpath <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",PNSC_sub[num,1],"/",PNSC_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("ivertex_sulc")
  newdata$subid <- PNSC_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  i_vertex <- rbind(i_vertex, newdata, deparse.level = 1)
}
#adding RTMSWM to dataframe(ivertex)
for(num in 1:53) {
  newpath <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",RTMSWM_sub[num,1],"/",RTMSWM_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("ivertex_sulc")
  newdata$subid <- RTMSWM_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  i_vertex <- rbind(i_vertex, newdata, deparse.level = 1)
}
#adding SPINS to dataframe(ivertex)
for(num in 1:67) {
  newpath <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",SPINS_sub[num,1],"/",SPINS_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("ivertex_sulc")
  newdata$subid <- SPINS_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  i_vertex <- rbind(i_vertex, newdata, deparse.level = 1)
}
#adding ZHH to dataframe(ivertex)
for(num in 1:301) {
  newpath <- (paste("/projects/dmiranda/sulc/i_vertex/output_ts/",ZHH_sub[num,1],"/",ZHH_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("ivertex_sulc")
  newdata$subid <- ZHH_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  i_vertex <- rbind(i_vertex, newdata, deparse.level = 1)
}
```

### Creating tvertex dataframe
```{r}
# creating initial dataframe (tvertex)
t_vertex <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",ASDD_sub[1,1],"/",ASDD_sub[1,1],".meants.csv",sep = ""))
t_vertex <- read.csv(t_vertex, header = FALSE)
colnames(t_vertex)<- c("tvertex_sulc")
t_vertex$subid <- ASDD_sub[1,1]
t_vertex$roiidx <- 1:nrow(data.frame(t_vertex))

#adding ASDD to dataframe(tvertex)
for(num in 2:15) {
  newpath <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",ASDD_sub[num,1],"/",ASDD_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("tvertex_sulc")
  newdata$subid <- ASDD_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  t_vertex <- rbind(t_vertex, newdata, deparse.level = 1)
}

#adding COBRE to dataframe(tvertex)
for(num in 1:112) {
  newpath <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",COBRE_sub[num,1],"/",COBRE_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("tvertex_sulc")
  newdata$subid <- COBRE_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  t_vertex <- rbind(t_vertex, newdata, deparse.level = 1)
}

#adding DTI3T to dataframe(tvertex)
for(num in 1:43) {
  newpath <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",DTI3T_sub[num,1],"/",DTI3T_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("tvertex_sulc")
  newdata$subid <- DTI3T_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  t_vertex <- rbind(t_vertex, newdata, deparse.level = 1)
}

#adding PNSC to dataframe(tvertex)
for(num in 1:7) {
  newpath <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",PNSC_sub[num,1],"/",PNSC_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("tvertex_sulc")
  newdata$subid <- PNSC_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  t_vertex <- rbind(t_vertex, newdata, deparse.level = 1)
}

#adding RTMSWM to dataframe(tvertex)
for(num in 1:53) {
  newpath <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",RTMSWM_sub[num,1],"/",RTMSWM_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("tvertex_sulc")
  newdata$subid <- RTMSWM_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  t_vertex <- rbind(t_vertex, newdata, deparse.level = 1)
}

#adding SPINS to dataframe(tvertex)
for(num in 1:67) {
  newpath <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",SPINS_sub[num,1],"/",SPINS_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("tvertex_sulc")
  newdata$subid <- SPINS_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  t_vertex <- rbind(t_vertex, newdata, deparse.level = 1)
}

#adding ZHH to dataframe(tvertex)
for(num in 1:301) {
  newpath <- (paste("/projects/dmiranda/sulc/t_vertex/output_ts/",ZHH_sub[num,1],"/",ZHH_sub[num,1],".meants.csv",sep = ""))
  newdata <- read.csv(newpath,header = FALSE)
  colnames(newdata)<- c("tvertex_sulc")
  newdata$subid <- ZHH_sub[num,1]
  newdata$roiidx <- 1:nrow(data.frame(newdata))
  t_vertex <- rbind(t_vertex, newdata, deparse.level = 1)
}

```

### Creating master dataframe with demographics
```{r}
# Merge T and I vertex
i_t_vertices <- merge(i_vertex, t_vertex, by=c('subid','roiidx'))
# Merge Demographics
Master_i_t <- merge(i_t_vertices,demographics, by='subid')
Master_i_t$X <- NULL 
Master_i_t$sex.x <- NULL
Master_i_t$name <- NULL
Master_i_t <- merge(Master_i_t, distance, by=c('subid','roiidx'))
```

### Subsetting into Schiz and Control
```{r}
schiz_i_t <- subset(Master_i_t, DX_GROUP==1)
control_i_t <- subset(Master_i_t, DX_GROUP==2)
```

### Averaging and grouping by roi
```{r}
library(dplyr)
library(ggplot2)
# summarising and grouping by roi
schiz_i_t_avg <- summarise(group_by(schiz_i_t,roiidx),i_sulc_mean=mean(ivertex_sulc),t_sulc_mean=mean(tvertex_sulc),t_sulc_sd=sd(tvertex_sulc),i_sulc_sd=sd(ivertex_sulc), dis_mean=mean(std_distance),dis_sd=sd(std_distance))
control_i_t_avg <- summarise(group_by(control_i_t,roiidx),i_sulc_mean=mean(ivertex_sulc),t_sulc_mean=mean(tvertex_sulc),t_sulc_sd=sd(tvertex_sulc),i_sulc_sd=sd(ivertex_sulc),dis_mean=mean(std_distance),dis_sd=sd(std_distance))
```

### Schiz cor
```{r}
cor(schiz_i_t_avg$i_sulc_mean, schiz_i_t_avg$dis_mean) #*
cor(schiz_i_t_avg$i_sulc_mean, schiz_i_t_avg$dis_sd) #*
cor(schiz_i_t_avg$i_sulc_sd, schiz_i_t_avg$dis_sd)
cor(schiz_i_t_avg$i_sulc_sd, schiz_i_t_avg$dis_mean)
cor(schiz_i_t_avg$t_sulc_mean, schiz_i_t_avg$dis_mean) #* 
cor(schiz_i_t_avg$t_sulc_mean, schiz_i_t_avg$dis_sd) #*
cor(schiz_i_t_avg$t_sulc_sd, schiz_i_t_avg$dis_sd)
cor(schiz_i_t_avg$t_sulc_sd, schiz_i_t_avg$dis_mean)
```

### Control cor
```{r}
cor(control_i_t_avg$i_sulc_mean, control_i_t_avg$dis_mean) #*
cor(control_i_t_avg$i_sulc_mean, control_i_t_avg$dis_sd) #*
cor(control_i_t_avg$i_sulc_sd, control_i_t_avg$dis_sd)
cor(control_i_t_avg$i_sulc_sd, control_i_t_avg$dis_mean)
cor(control_i_t_avg$t_sulc_mean, control_i_t_avg$dis_mean) #*
cor(control_i_t_avg$t_sulc_mean, control_i_t_avg$dis_sd) #*
cor(control_i_t_avg$t_sulc_sd, control_i_t_avg$dis_sd)
cor(control_i_t_avg$t_sulc_sd, control_i_t_avg$dis_mean)
```

## Plots for i_sulc_mean and dis_mean
```{r i_sulcmean_dismean_schiz}
# r= -0.3516408
schiz_roi <- ggplot(schiz_i_t_avg, aes(i_sulc_mean,dis_mean)) +  ggtitle("schiz_rois r= -0.3516408") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0) + coord_cartesian(ylim=c(5.8,11.5),xlim = c(-2.5,1.9))
schiz_roi
```
```{r i_sulcmean_dismean_control}
# r =-0.3091869
con_roi <- ggplot(control_i_t_avg, aes(i_sulc_mean,dis_mean)) +  ggtitle("control_rois r =-0.3091869") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0) + coord_cartesian(ylim=c(5.8,11.5),xlim = c(-2.5,1.9))
con_roi

```

## Plots for i_sulc_mean and dis_sd
```{r i_sulcmean_dissd_contr}
# r =-0.3301919
schiz_roi <- ggplot(schiz_i_t_avg, aes(i_sulc_mean,dis_sd)) +  ggtitle("schiz_rois r =-0.3301919") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0)  + coord_cartesian(ylim=c(3.3,6.7),xlim = c(-2.5,1.9))
schiz_roi
```
```{r i_sulcmean_dissd_schiz}
# r= -0.3042098
con_roi <- ggplot(control_i_t_avg, aes(i_sulc_mean,dis_sd)) +  ggtitle("control_rois r= -0.3042098") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0)  + coord_cartesian(ylim=c(3.3,6.7),xlim = c(-2.5,1.9))
con_roi
```

## Plots for t_sulc_mean and dis_mean
```{r t_sulcmean_dismean_schiz}
# r= -0.3278741
schiz_roi <- ggplot(schiz_i_t_avg, aes(t_sulc_mean,dis_mean)) +  ggtitle("schiz_rois r= -0.3278741") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0) + coord_cartesian(ylim=c(5.8,11.5),xlim = c(-3.2,2.6))
schiz_roi
# r= -0.2969104
```
```{r t_sulcmean_dismean_contr}
con_roi <- ggplot(control_i_t_avg, aes(t_sulc_mean,dis_mean)) +  ggtitle("control_rois r= -0.2969104") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0) + coord_cartesian(ylim=c(5.8,11.5),xlim = c(-3.2,2.6))
con_roi

```

## Plots for t_sulc_mean and dis_sd
```{r t_sulcmean_dissd_schiz}
# r=-0.1950672
schiz_roi <- ggplot(schiz_i_t_avg, aes(t_sulc_mean,dis_sd)) +  ggtitle("schiz_rois r=-0.1950672") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0)+ coord_cartesian(ylim=c(3.3,6.7),xlim = c(-3.4,2.9)) 
schiz_roi
```
```{r t_sulcmean_dissd_contr}
#r=-0.2156565
con_roi <- ggplot(control_i_t_avg, aes(t_sulc_mean,dis_sd)) +  ggtitle("control_rois r=-0.2156565") + geom_point() + geom_smooth(method='lm') + geom_text(aes(label=roiidx),hjust=0, vjust=0) + coord_cartesian(ylim=c(3.3,6.7),xlim = c(-3.4,2.9)) 
con_roi
```
