---
title: "04 PINT displacement stats"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    keep_md: true
    df_print: paged
---

# Stats on the PINT summary displacement values

```{r}
library(tidyverse)
library(broom)
library(here)
```


## The paths to data

```{r setting paths}
source(here('code/R/settings_helpers.R'))

Yeo7_2011_80verts <- read_Yeo72011_template()

YeoNet_colours = define_Yeo7_colours()

## adding a subid that matches what the concatenation script adds..
pheno <- read_pheno_file() %>%
  mutate(subid = str_replace(filename, '_summary.csv','')) %>%
  drop_na(DX) %>%
  drop_na(Age_match) # dropping un-matched subjects

#pint_concat <- read_csv(file.path(output_base,'postPINT1_concat_all_qa_passes.csv'))
pint_concat <- read_csv(here("data","processed","mri",
              "all_clinicalplusqa_group", "postPINT",
              "postPINT1_concat_all_qa_passes.csv"))

lm_predictors <- "DX + Age_match_pt + Sex + fd_mean_match_pt + Site + SurfArea_match_pt"
```




```{r}
ana_data <- pheno %>%
  inner_join(pint_concat, by = "subid") %>%
  inner_join(Yeo7_2011_80verts, by = "roiidx") %>%
  mutate(network = str_sub(SHORTNAME, 1,2))

```


## run for the whole head

```{r}
dist_by_total <- ana_data %>%
  group_by(subid) %>%
  summarise(MeanDistance = mean(std_distance)) %>%
  ungroup() %>%
  inner_join(pheno, by = "subid") 

dist_by_total %>%
  ungroup() %>%
  do(tidy(lm(formula(paste("MeanDistance ~", lm_predictors)),.))) %>%
  knitr::kable()
```

```{r age-location-plot-byDX, fig.height=4, fig.width=7}
dist_by_total %>%
  ggplot(aes(y = MeanDistance, x = Age)) +
  geom_point(aes(color = Site)) + 
  geom_smooth(aes(color = DX), method = "lm")+
  facet_wrap(~DX) +
  theme_bw()
```
```{r age-location-plot-byDX-blackred, fig.height=4, fig.width=5}
dist_by_total %>%
  ggplot(aes(y = MeanDistance, x = Age, color = DX)) +
  geom_point() + 
  geom_smooth(method = "lm")+
  scale_color_manual(values = c("grey20","red")) +
  theme_bw()
```


```{r, fig.height=4, fig.width=6}
dist_by_total %>%
  ggplot(aes(y = MeanDistance, x = DX, color = DX)) + 
  geom_boxplot(outlier.shape = NA) + 
  geom_dotplot(binaxis = 'y', stackdir = 'center', binwidth = 0.08, alpha = 0.5) +
  scale_color_manual(values = c("grey20","red")) +
  facet_wrap( ~ Site, ncol = 4) +
  labs(x = NULL) +
  theme_minimal()
```



```{r}
dist_by_network <- pint_concat %>%
  inner_join(Yeo7_2011_80verts, by = "roiidx") %>%
  mutate(network = str_sub(SHORTNAME, 1,2)) %>%
  group_by(subid, network) %>%
  summarise(MeanDistance = mean(std_distance)) %>%
  ungroup() %>%
  inner_join(pheno, by = "subid")  

dist_by_network_lmfit <- dist_by_network %>%
  ungroup() %>% group_by(network) %>%
  do(tidy(lm(formula(paste("MeanDistance ~", lm_predictors)),.))) %>%
  mutate(p_bonf = p.value*6)

dist_by_network_lmfit %>%
  filter(!(term %in% c('(Intercept)', 'SiteCOBRE', 'Siteds000030', 'SiteZHH'))) %>%
  #select(network, term, df, statistic, p.value, p_bonf) %>%
  arrange(term, network) %>%
  knitr::kable()
```





```{r age-loc_dx-plot_by_network, fig.height=3, fig.width = 10}

dist_by_network %>%
  ggplot(aes(y = MeanDistance, x = Age)) +
  geom_point(alpha = 0.2, size = 0.5) + 
  geom_smooth(aes(color = DX), method = "lm") +
  facet_wrap(~network, scales = "free", nrow = 1) +
  scale_color_manual(values = c("grey20","red"))+
  theme_minimal()
  
```


## run linear model per edge

```{r}

roi_dx_lm <- ana_data %>%
  ungroup() %>% group_by(SHORTNAME) %>%
  do(tidy(lm(formula(paste("std_distance ~", lm_predictors)),.))) %>%
  ungroup() %>% group_by(term) %>%
  mutate(p_fdr  = p.adjust(p.value, method = 'fdr'))

roi_dx_lm %>%
  filter(term %in% c("DXSSD")) %>%
  filter(p_fdr < 0.1)
```
```{r}
roi_dx_lm %>%
  filter(term %in% c("Age_match_pt")) %>%
  filter(p_fdr < 0.1)
```

