---
title: "Cortial-cortical Stats"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    keep_md: yes
---

Checking how the cortical-cortical stats change with adding surfaced based analyses and PINT

```{r}
library(tidyverse)
library(broom)
library(knitr)
library(cowplot)
library(ggridges)
library(igraph)
```

```{r setting paths}
source('../R/settings_helpers.R')
pheno <- read_pheno_file()
YeoNet_colours <- define_Yeo7_colours()
Yeo7_2011_80verts <- read_Yeo72011_template()
the_subcortical_guide <- get_subcortical_guide()
node_annotations <- get_node_annotations(Yeo7_2011_80verts, the_subcortical_guide)
source('../R/file_reading_helpers.R')
source('../R/custom_plot_helpers.R')
```


```{r}
pheno <- pheno %>%
  mutate(func_base = get_func_base_from_pint_summary_filename(filename,subject, session), 
         outputprefix = construct_output_prefix(subject, session, func_base)) 
```

```{r eval = FALSE}
map2(pheno$outputprefix[1], pheno$dataset[1],
                              ~run_read_all_subject_timeseries_and_cortcort_corZ(.x, .y))
```

```{r read all the data}

all_corZ_results <- pheno %>%
  select(subject, outputprefix, dataset) %>%
  mutate(the_corrs = map2(.$outputprefix, .$dataset,
                              ~run_read_all_subject_timeseries_and_cortcort_corZ(.x, .y)))
```

```{r}
#' convert from three col graph df to adjacency matrix
uppertri_df_to_agjmat <- function(graph_df) {
  
names(graph_df) <- c('to', 'from', 'myattr')
matrix_out <- graph_df %>%
  graph_from_data_frame(.,directed = F) %>%
  get.adjacency(., type = "both", attr = "myattr") %>%
  as.matrix() 
return(matrix_out)
}

#' go uppertri data to full dataframe for geom_tile
uppertri_df_to_full <- function(graph_df) {
result <- graph_df %>%
  uppertri_df_to_agjmat() %>%
  as.data.frame() %>%
  mutate(to = row.names(.)) %>%
  gather(from, value, -to) 
return(result)
}
```

```{r}
mean_cors <- all_corZ_results %>%
  unnest() %>%
  group_by(vertex_type, to, from) %>%
  summarise(mcorZ = mean(weight))
```


```{r mean_cortical_matrixes, fig.height=6, fig.width=7.5}

mean_cors %>%
  filter(vertex_type == "pvertex") %>%
  withincortical_heatmap("Personalized Mean Correlation", mcorZ) %>%
  ggdraw()

mean_cors %>%
  filter(vertex_type == "tvertex") %>%
  withincortical_heatmap("Surface Template Mean Correlation", mcorZ) %>%
  ggdraw()

mean_cors %>%
  filter(vertex_type == "tvolume") %>%
  withincortical_heatmap("Volume Template Mean Correlation", mcorZ) %>%
  ggdraw()
```


```{r repsub1-cor-mats, fig.height=6, fig.width=7.5}

thissubject = unique(pheno$subject)[2]

this_results_pheno <- all_corZ_results %>%
  filter(subject==thissubject) %>%
  unnest()

this_results_pheno %>%
  filter(vertex_type == "pvertex") %>%
  withincortical_heatmap(str_c(thissubject, " Personalized Correlation")) %>%
  ggdraw()

this_results_pheno %>%
  filter(vertex_type == "tvertex") %>%
  withincortical_heatmap(str_c(thissubject, " Surface Template Correlation")) %>%
  ggdraw()

this_results_pheno %>%
  filter(vertex_type == "tvolume") %>%
  withincortical_heatmap(str_c(thissubject, " Volume Template Correlation")) %>%
  ggdraw()

```

```{r repsub2-cor-mats, fig.height=6, fig.width=7.5}

thissubject = unique(pheno$subject)[3]

this_results_pheno <- all_corZ_results %>%
  filter(subject==thissubject) %>%
  unnest()

this_results_pheno %>%
  filter(vertex_type == "pvertex") %>%
  withincortical_heatmap(str_c(thissubject, " Personalized Correlation")) %>%
  ggdraw()

this_results_pheno %>%
  filter(vertex_type == "tvertex") %>%
  withincortical_heatmap(str_c(thissubject, " Surface Template Correlation")) %>%
  ggdraw()

this_results_pheno %>%
  filter(vertex_type == "tvolume") %>%
  withincortical_heatmap(str_c(thissubject, " Volume Template Correlation")) %>%
  ggdraw()

```

```{r repsub3-cor-mats, fig.height=6, fig.width=7.5}

thissubject = unique(pheno$subject)[100]

this_results_pheno <- all_corZ_results %>%
  filter(subject==thissubject) %>%
  unnest()

this_results_pheno %>%
  filter(vertex_type == "pvertex") %>%
  withincortical_heatmap(str_c(thissubject, " Personalized Correlation")) %>%
  ggdraw()

this_results_pheno %>%
  filter(vertex_type == "tvertex") %>%
  withincortical_heatmap(str_c(thissubject, " Surface Template Correlation")) %>%
  ggdraw()

this_results_pheno %>%
  filter(vertex_type == "tvolume") %>%
  withincortical_heatmap(str_c(thissubject, " Volume Template Correlation")) %>%
  ggdraw()

```

## To do - rainclouds for withing between changes in cortical cortical??


