<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Code for reading in all the timeseries.. | SSD PINT analyses</title>
  <meta name="description" content="This contains the analysis reported with the SSD pint paper" />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Code for reading in all the timeseries.. | SSD PINT analyses" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This contains the analysis reported with the SSD pint paper" />
  <meta name="github-repo" content="https://github.com/TIGRLab/STOP-PD_ACNP" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Code for reading in all the timeseries.. | SSD PINT analyses" />
  
  <meta name="twitter:description" content="This contains the analysis reported with the SSD pint paper" />
  

<meta name="author" content="Erin Dickie" />


<meta name="date" content="2020-06-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="whole-connectome-results.html"/>
<link rel="next" href="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R-stats in SSD PINT paper</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> The index page</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#all-the-packages-in-this-book"><i class="fa fa-check"></i><b>1.1</b> all the packages in this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html"><i class="fa fa-check"></i><b>2</b> Mangle participant demographics</a><ul>
<li class="chapter" data-level="2.0.1" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html#mangle-the-zzh-data---determining-the-mapping-between-the-zhh-session-name-and-daytons-bids-name"><i class="fa fa-check"></i><b>2.0.1</b> mangle the ZZH data - determining the mapping between the ZHH session name and Dayton's bids name</a></li>
<li class="chapter" data-level="2.1" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html#coding-zhh-data-by-session"><i class="fa fa-check"></i><b>2.1</b> Coding ZHH data by session</a></li>
<li class="chapter" data-level="2.2" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html#note---re-picking-motion-cutoffs"><i class="fa fa-check"></i><b>2.2</b> Note - re picking motion cutoffs</a></li>
<li class="chapter" data-level="2.3" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html#now-looking-at-what-we-have-from-cobre"><i class="fa fa-check"></i><b>2.3</b> Now looking at what we have from COBRE</a></li>
<li class="chapter" data-level="2.4" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html#now-looking-at-the-cnp-we-have.."><i class="fa fa-check"></i><b>2.4</b> Now looking at the CNP we have..</a></li>
<li class="chapter" data-level="2.5" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html#add-where-are-is-the-cmh-demographic-info.."><i class="fa fa-check"></i><b>2.5</b> add where are is the CMH demographic info..</a></li>
<li class="chapter" data-level="2.6" data-path="mangle-participant-demographics.html"><a href="mangle-participant-demographics.html#extra-little-bit-for-traking-down-missing-cobre"><i class="fa fa-check"></i><b>2.6</b> extra little bit for traking down &quot;missing&quot; COBRE</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html"><i class="fa fa-check"></i><b>3</b> Check completion and add MR QA</a><ul>
<li class="chapter" data-level="3.1" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#get-a-list-of-available-bold-and-t1w-files-from-the-mriqc-outputs"><i class="fa fa-check"></i><b>3.1</b> Get a list of available bold and T1w files (from the mriqc outputs)</a><ul>
<li class="chapter" data-level="3.1.1" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#the-list-of-usable-scans-is-all-participants-with-both-t1w-and-bold-data"><i class="fa fa-check"></i><b>3.1.1</b> the list of usable scans is all participants with both T1w and bold data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#now-glob-for-all-of-the-pint-outputs"><i class="fa fa-check"></i><b>3.2</b> now glob for all of the PINT outputs</a></li>
<li class="chapter" data-level="3.3" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#read-in-the-combined-demographics-from-the-last-chapter"><i class="fa fa-check"></i><b>3.3</b> read in the combined demographics from the last chapter</a></li>
<li class="chapter" data-level="3.4" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#also-read-in-an-concatenate-all-the-surface-area-info-from-freesurfer"><i class="fa fa-check"></i><b>3.4</b> also read in an concatenate all the surface area info from freesurfer</a></li>
<li class="chapter" data-level="3.5" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#anti-join-the-pheno-data-with-the-usable-scan-data-to-see-if-we-have-everything.."><i class="fa fa-check"></i><b>3.5</b> anti-join the pheno data with the usable scan data to see if we have everything..</a></li>
<li class="chapter" data-level="3.6" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#zhh-is-the-only-site-where-we-have-session-specific-pheno-information..-so-we-will-check-that"><i class="fa fa-check"></i><b>3.6</b> ZHH is the only site where we have session specific pheno information.. so we will check that</a></li>
<li class="chapter" data-level="3.7" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#setting-the-motion-threshold"><i class="fa fa-check"></i><b>3.7</b> Setting the motion threshold:</a></li>
<li class="chapter" data-level="3.8" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#write-this-table-out-to-csv---than-read-the-csv-and-print-it"><i class="fa fa-check"></i><b>3.8</b> write this table out to csv - than read the csv and print it</a></li>
<li class="chapter" data-level="3.9" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#who-is-still-missing-a-pint-output"><i class="fa fa-check"></i><b>3.9</b> who is still missing a PINT output?</a></li>
<li class="chapter" data-level="3.10" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#selecting-scans-with-least-motion"><i class="fa fa-check"></i><b>3.10</b> Selecting scans with least motion</a></li>
<li class="chapter" data-level="3.11" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#final-mangle-of-the-phenotypic-data-transforming-variables"><i class="fa fa-check"></i><b>3.11</b> final mangle of the phenotypic data (transforming variables)</a></li>
<li class="chapter" data-level="3.12" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#adding-matching-for-the-ds00030-subsample-first..."><i class="fa fa-check"></i><b>3.12</b> adding matching for the ds00030 subsample first...</a><ul>
<li class="chapter" data-level="3.12.1" data-path="check-completion-and-add-mr-qa.html"><a href="check-completion-and-add-mr-qa.html#write-out-subject-list-for-further-analysis"><i class="fa fa-check"></i><b>3.12.1</b> write out subject list for further analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="stats-on-the-pint-summary-displacement-values.html"><a href="stats-on-the-pint-summary-displacement-values.html"><i class="fa fa-check"></i><b>4</b> Stats on the PINT summary displacement values</a><ul>
<li class="chapter" data-level="4.1" data-path="stats-on-the-pint-summary-displacement-values.html"><a href="stats-on-the-pint-summary-displacement-values.html#the-paths-to-data"><i class="fa fa-check"></i><b>4.1</b> The paths to data</a></li>
<li class="chapter" data-level="4.2" data-path="stats-on-the-pint-summary-displacement-values.html"><a href="stats-on-the-pint-summary-displacement-values.html#run-for-the-whole-head"><i class="fa fa-check"></i><b>4.2</b> run for the whole head</a></li>
<li class="chapter" data-level="4.3" data-path="stats-on-the-pint-summary-displacement-values.html"><a href="stats-on-the-pint-summary-displacement-values.html#double-check-that-modelplot-look-right-without-cobre-and-ds00030"><i class="fa fa-check"></i><b>4.3</b> double check that model/plot look right without COBRE and ds00030</a></li>
<li class="chapter" data-level="4.4" data-path="stats-on-the-pint-summary-displacement-values.html"><a href="stats-on-the-pint-summary-displacement-values.html#run-linear-model-per-edge-not-reported"><i class="fa fa-check"></i><b>4.4</b> run linear model per edge (not reported)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sub-cortical-cortical-stats-left-and-right.html"><a href="sub-cortical-cortical-stats-left-and-right.html"><i class="fa fa-check"></i><b>5</b> Sub-cortical Cortical Stats Left and Right</a><ul>
<li class="chapter" data-level="5.1" data-path="sub-cortical-cortical-stats-left-and-right.html"><a href="sub-cortical-cortical-stats-left-and-right.html#the-paths-to-data-1"><i class="fa fa-check"></i><b>5.1</b> The paths to data</a><ul>
<li class="chapter" data-level="5.1.1" data-path="sub-cortical-cortical-stats-left-and-right.html"><a href="sub-cortical-cortical-stats-left-and-right.html#this-reads-all-the-subcortical-files-it-can-find"><i class="fa fa-check"></i><b>5.1.1</b> This reads all the subcortical files it can find</a></li>
<li class="chapter" data-level="5.1.2" data-path="sub-cortical-cortical-stats-left-and-right.html"><a href="sub-cortical-cortical-stats-left-and-right.html#reduce-data-from-the-whole-brain-data-to-only-include-the-subcortical-cortical-connections"><i class="fa fa-check"></i><b>5.1.2</b> reduce data from the whole brain data to only include the subcortical cortical connections</a></li>
<li class="chapter" data-level="5.1.3" data-path="sub-cortical-cortical-stats-left-and-right.html"><a href="sub-cortical-cortical-stats-left-and-right.html#merge-with-the-phenotypic-data"><i class="fa fa-check"></i><b>5.1.3</b> merge with the phenotypic data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sub-cortical-cortical-stats-left-and-right.html"><a href="sub-cortical-cortical-stats-left-and-right.html#make-a-subject-table-from-resuts-pheno"><i class="fa fa-check"></i><b>5.2</b> make a subject table from resuts pheno</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="is-pint-focusing-cortical-subcortical-connectivity.html"><a href="is-pint-focusing-cortical-subcortical-connectivity.html"><i class="fa fa-check"></i><b>6</b> Is PINT &quot;focusing&quot; cortical subcortical connectivity</a></li>
<li class="chapter" data-level="7" data-path="cortical-cortical-results.html"><a href="cortical-cortical-results.html"><i class="fa fa-check"></i><b>7</b> Cortical-cortical results</a><ul>
<li class="chapter" data-level="7.1" data-path="cortical-cortical-results.html"><a href="cortical-cortical-results.html#to-do---rainclouds-for-withing-between-changes-in-cortical-cortical"><i class="fa fa-check"></i><b>7.1</b> To do - rainclouds for withing between changes in cortical cortical??</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="whole-connectome-results.html"><a href="whole-connectome-results.html"><i class="fa fa-check"></i><b>8</b> Whole Connectome Results</a><ul>
<li class="chapter" data-level="8.1" data-path="whole-connectome-results.html"><a href="whole-connectome-results.html#the-paths-to-data-2"><i class="fa fa-check"></i><b>8.1</b> The paths to data</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html"><i class="fa fa-check"></i><b>9</b> Code for reading in all the timeseries..</a><ul>
<li class="chapter" data-level="9.1" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#this-was-run-once-in-order-to-detemine-the-too-small-subcortical-rois"><i class="fa fa-check"></i><b>9.1</b> This was run once in order to detemine the too small subcortical ROIs</a><ul>
<li class="chapter" data-level="9.1.1" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#this-reads-all-the-subcortical-files-it-can-find-1"><i class="fa fa-check"></i><b>9.1.1</b> This reads all the subcortical files it can find</a></li>
<li class="chapter" data-level="9.1.2" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#merge-with-the-phenotypic-data-1"><i class="fa fa-check"></i><b>9.1.2</b> merge with the phenotypic data</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#calcualate-cohens-d-for-diagnosis-effect"><i class="fa fa-check"></i><b>9.2</b> calcualate cohen's D for Diagnosis Effect</a></li>
<li class="chapter" data-level="9.3" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#filters-out-some-unwanted-edges-before-fdr-correction"><i class="fa fa-check"></i><b>9.3</b> filters out some unwanted edges before FDR correction</a></li>
<li class="chapter" data-level="9.4" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#make-co"><i class="fa fa-check"></i><b>9.4</b> Make co</a></li>
<li class="chapter" data-level="9.5" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#make-table-fdr-corrected-edges-that-survive-correction"><i class="fa fa-check"></i><b>9.5</b> make table FDR corrected Edges that survive correction</a><ul>
<li class="chapter" data-level="9.5.1" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#calculated-extract-edge-weights-for-per-participant-scores"><i class="fa fa-check"></i><b>9.5.1</b> calculated extract edge weights for per participant scores</a></li>
<li class="chapter" data-level="9.5.2" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#calculated-scores-per-participant"><i class="fa fa-check"></i><b>9.5.2</b> calculated scores per participant</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="code-for-reading-in-all-the-timeseries-.html"><a href="code-for-reading-in-all-the-timeseries-.html#write-up-to-this-point.."><i class="fa fa-check"></i><b>9.6</b> write up to this point..</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html"><a href="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html"><i class="fa fa-check"></i><b>10</b> calculate weighted subject scores by chopping up the matrix</a><ul>
<li class="chapter" data-level="10.1" data-path="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html"><a href="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html#the-paths-to-data-3"><i class="fa fa-check"></i><b>10.1</b> The paths to data</a><ul>
<li class="chapter" data-level="10.1.1" data-path="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html"><a href="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html#refit-the-models-with-education-included"><i class="fa fa-check"></i><b>10.1.1</b> refit the models with Education included</a></li>
<li class="chapter" data-level="10.1.2" data-path="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html"><a href="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html#the-results-write-up"><i class="fa fa-check"></i><b>10.1.2</b> The results write-up</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SSD PINT analyses</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="code-for-reading-in-all-the-timeseries.." class="section level1">
<h1><span class="header-section-number">Chapter 9</span> Code for reading in all the timeseries..</h1>
<p>A table that describes the current expected subortical files</p>
<p>These functions are for reading timeseries files</p>
<p>This reads all files and generate PINT to subcortical correlation values for a given subject</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">the_subcortical_guide &lt;-<span class="st"> </span><span class="kw">get_subcortical_guide</span>()</code></pre></div>
<pre><code>## Warning: `cols` is now required when using unnest().
## Please use `cols = c(subcort_NET)`</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   subcort_hemi = col_character(),
##   subcort_ROI = col_character(),
##   numvx = col_double(),
##   network = col_character()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#run_read_subject_subcort_corrs(subcort_outputlist$subid[1])</span></code></pre></div>
<div id="this-was-run-once-in-order-to-detemine-the-too-small-subcortical-rois" class="section level2">
<h2><span class="header-section-number">9.1</span> This was run once in order to detemine the too small subcortical ROIs</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">read_vx_count &lt;-<span class="st"> </span><span class="cf">function</span>(filepath) {
  <span class="kw">read_csv</span>(filepath, <span class="dt">col_names =</span> <span class="ot">FALSE</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">network =</span> <span class="kw">c</span>(<span class="st">&#39;VI&#39;</span>,<span class="st">&#39;SM&#39;</span>,<span class="st">&#39;DA&#39;</span>,<span class="st">&#39;VA&#39;</span>, <span class="st">&#39;LI&#39;</span>,<span class="st">&#39;FP&#39;</span>,<span class="st">&#39;DM&#39;</span>)) 
}

vx_counts &lt;-<span class="st"> </span>the_subcortical_guide <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subcort_hemi, subcort_ROI) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">distinct</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">vx_count =</span> <span class="kw">str_c</span>(output_base,<span class="st">&#39;/ZHH/out/ciftify_meants/templates/7RSN_roi-&#39;</span>,subcort_hemi, subcort_ROI,<span class="st">&#39;_vxcount.txt&#39;</span>)) <span class="op">%&gt;%</span>
<span class="kw">mutate</span>(<span class="dt">vxnum =</span> <span class="kw">map</span>(vx_count, <span class="op">~</span><span class="kw">read_vx_count</span>(.x))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subcort_hemi, subcort_ROI, X1, network) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">numvx =</span> X1)

<span class="kw">write_csv</span>(vx_counts, <span class="st">&#39;../templates/subcort_vxcounts.csv&#39;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">node_annotations &lt;-<span class="st"> </span><span class="kw">get_node_annotations</span>(Yeo7_2011_80verts, the_subcortical_guide)</code></pre></div>
<div id="this-reads-all-the-subcortical-files-it-can-find-1" class="section level3">
<h3><span class="header-section-number">9.1.1</span> This reads all the subcortical files it can find</h3>
<p>Write a func_base and outputprefix cols into the pheno file for the file reading step</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&#39;code/R/file_reading_helpers.R&#39;</span>))
pheno &lt;-<span class="st"> </span>pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">func_base =</span> <span class="kw">get_func_base_from_pint_summary_filename</span>(filename,subject, session), 
         <span class="dt">outputprefix =</span> <span class="kw">construct_output_prefix</span>(subject, session, func_base))
<span class="kw">map2</span>(pheno<span class="op">$</span>outputprefix[<span class="dv">1</span>], pheno<span class="op">$</span>dataset[<span class="dv">1</span>],
                              <span class="op">~</span><span class="kw">run_read_all_subject_timeseries_and_wholebrain_corZ</span>(.x, .y))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&#39;code/R/file_reading_helpers.R&#39;</span>))
pheno &lt;-<span class="st"> </span>pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">func_base =</span> <span class="kw">get_func_base_from_pint_summary_filename</span>(filename,subject, session), 
         <span class="dt">outputprefix =</span> <span class="kw">construct_output_prefix</span>(subject, session, func_base))
all_corZ_results &lt;-<span class="st"> </span>pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subject, outputprefix, dataset) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">the_corrs =</span> <span class="kw">map2</span>(.<span class="op">$</span>outputprefix, .<span class="op">$</span>dataset,
                              <span class="op">~</span><span class="kw">run_read_all_subject_timeseries_and_wholebrain_corZ</span>(.x, .y)))

<span class="co">#save(all_corZ_results, file = file.path(output_base, &quot;all_clinicalplusqa_group&quot;, &quot;Rdata_cache&quot;, &quot;06_wholebrain_results_cache.Rdata&quot;))</span>
<span class="kw">saveRDS</span>(all_corZ_results, <span class="dt">file =</span> <span class="kw">file.path</span>(output_base, <span class="st">&quot;all_clinicalplusqa_group&quot;</span>, <span class="st">&quot;Rdata_cache&quot;</span>, <span class="st">&quot;06_wholebrain_FC_cache.rds&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="kw">file.path</span>(output_base, <span class="st">&quot;all_clinicalplusqa_group&quot;</span>, <span class="st">&quot;Rdata_cache&quot;</span>, <span class="st">&quot;06_wholebrain_results_cache.Rdata&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">all_corZ_results &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="dt">file =</span> <span class="kw">file.path</span>(output_base, <span class="st">&quot;all_clinicalplusqa_group&quot;</span>, <span class="st">&quot;Rdata_cache&quot;</span>, <span class="st">&quot;06_wholebrain_FC_cache.rds&quot;</span>))</code></pre></div>
</div>
<div id="merge-with-the-phenotypic-data-1" class="section level3">
<h3><span class="header-section-number">9.1.2</span> merge with the phenotypic data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">results_pheno &lt;-<span class="st"> </span>all_corZ_results <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(pheno, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;dataset&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest</span>(<span class="dt">cols =</span> <span class="kw">c</span>(the_corrs))  </code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">results_pheno</code></pre></div>
</div>
</div>
<div id="calcualate-cohens-d-for-diagnosis-effect" class="section level2">
<h2><span class="header-section-number">9.2</span> calcualate cohen's D for Diagnosis Effect</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(modelr)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;modelr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:igraph&#39;:
## 
##     permute</code></pre>
<pre><code>## The following object is masked from &#39;package:broom&#39;:
## 
##     bootstrap</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(effsize)


calc_DX_cohenD &lt;-<span class="st"> </span><span class="cf">function</span>(df, outcome, predictor, covars) { 
m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">formula</span>(<span class="kw">paste</span>(outcome, <span class="st">&#39;~&#39;</span>, <span class="kw">paste</span>(covars, <span class="dt">collapse =</span> <span class="st">&quot; + &quot;</span>))),
         <span class="dt">data =</span> df)
result &lt;-df <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">add_residuals</span>(m1) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">cohen.d</span>(<span class="kw">formula</span>(<span class="kw">paste</span>(<span class="st">&quot;resid ~&quot;</span>, predictor)), <span class="dt">data =</span> .) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>.<span class="op">$</span>estimate
<span class="kw">return</span>(result)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(all_corZ_results)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">results_pheno_plus_DXd &lt;-<span class="st"> </span><span class="cf">function</span>(results_pheno) {
  results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">semi_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">semi_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">corZ =</span> weight) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(vertex_type, to, from) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co">#slice(1:3) %&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">DX_cohenD =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="kw">calc_DX_cohenD</span>(.x, 
                                               <span class="dt">outcome =</span> <span class="st">&quot;corZ&quot;</span>, 
                                               <span class="dt">predictor =</span> <span class="st">&quot;DX&quot;</span>,
                                               <span class="dt">covars =</span> lm_covar_cols))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest</span>(DX_cohenD) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(vertex_type, to, from, DX_cohenD)
}

## had to split this by vertex because of RAM issues on laptop
pvertex_DXd &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">results_pheno_plus_DXd</span>()
tvertex_DXd &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">results_pheno_plus_DXd</span>()
tvolume_DXd &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvolume&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">results_pheno_plus_DXd</span>()

DX_cohensD_results &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(
  pvertex_DXd,
  tvertex_DXd,
  tvolume_DXd
) </code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_formula &lt;-<span class="st"> </span><span class="kw">formula</span>(<span class="kw">paste</span>(<span class="st">&quot;corZ ~ &quot;</span>, lm_predictor_col, <span class="st">&quot;+&quot;</span>,
                               <span class="kw">paste</span>(lm_covar_cols, <span class="dt">collapse =</span> <span class="st">&quot; + &quot;</span>)))

<span class="kw">print</span>(<span class="kw">str_glue</span>(<span class="st">&quot;fitting: lm formula {DX_lm_formula}&quot;</span>))</code></pre></div>
<pre><code>## fitting: lm formula ~
## fitting: lm formula corZ
## fitting: lm formula DX + Age_match_pt + Sex + fd_mean_match_pt + Site</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_fit &lt;-<span class="st"> </span><span class="cf">function</span>(results_pheno) {
  results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">semi_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">semi_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">corZ =</span> weight) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(vertex_type, to, from) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="kw">tidy</span>(<span class="kw">lm</span>(DX_lm_formula,.))) 
}

## had to split this by vertex because of RAM issues on laptop
pvertex_DX_lm &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">DX_lm_model_fit</span>()
tvertex_DX_lm &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">DX_lm_model_fit</span>()
tvolume_DX_lm &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvolume&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">DX_lm_model_fit</span>()

DX_lm_model_full &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(
  pvertex_DX_lm,
  tvertex_DX_lm,
  tvolume_DX_lm
) </code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_formula</code></pre></div>
<pre><code>## corZ ~ DX + Age_match_pt + Sex + fd_mean_match_pt + Site</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">annotated_graph_edges &lt;-<span class="st"> </span>DX_lm_model_full <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(to, from) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">distinct</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>), <span class="dt">suffix =</span> <span class="kw">c</span>(<span class="st">&#39;_to&#39;</span>,<span class="st">&#39;_from&#39;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unite</span>(from_to_type, etype_from, etype_to) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unite</span>(hemis, hemi_from, hemi_to, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unite</span>(networks, network_from, network_to, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>, <span class="dt">remove =</span> <span class="ot">FALSE</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">from_to_type =</span> <span class="kw">recode</span>(from_to_type, <span class="st">&quot;Cort_SubCort&quot;</span> =<span class="st"> &quot;SubCort_Cort&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hemis =</span> <span class="kw">recode</span>(hemis, <span class="st">&quot;RL&quot;</span> =<span class="st"> &quot;LR&quot;</span>)) </code></pre></div>
</div>
<div id="filters-out-some-unwanted-edges-before-fdr-correction" class="section level2">
<h2><span class="header-section-number">9.3</span> filters out some unwanted edges before FDR correction</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model &lt;-<span class="st"> </span>DX_lm_model_full <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(annotated_graph_edges, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>, <span class="st">&quot;from&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">withinsubcort =</span> <span class="kw">if_else</span>((from_to_type <span class="op">==</span><span class="st"> &quot;SubCort_SubCort&quot;</span>) <span class="op">&amp;</span><span class="st"> </span>(subcort_ROI_from <span class="op">==</span><span class="st"> </span>subcort_ROI_to), <span class="st">&quot;drop&quot;</span>, <span class="st">&quot;keep&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(withinsubcort <span class="op">==</span><span class="st"> &quot;keep&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(vertex_type, to, from, term, statistic, p.value) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(term) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_FDR =</span> <span class="kw">p.adjust</span>(p.value, <span class="dt">method =</span> <span class="st">&quot;fdr&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(p.value)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD &lt;-<span class="st"> </span>DX_lm_model <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(DX_cohensD_results, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;vertex_type&quot;</span>, <span class="st">&quot;to&quot;</span>, <span class="st">&quot;from&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">cohenD_DX_tstatdir =</span> <span class="op">-</span><span class="dv">1</span> <span class="op">*</span><span class="st"> </span>DX_cohenD)
DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(cohenD_DX_tstatdir, statistic, <span class="dt">color =</span> (p_FDR <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>))) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(p_FDR <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(p.value)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>)</code></pre></div>
<pre><code>## # A tibble: 5 x 9
## # Groups:   term [1]
##   vertex_type to    from  term  statistic p.value  p_FDR DX_cohenD
##   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 tvertex     DMT1L DAP3R DXSSD     -2.76 0.00603 0.0500     0.268
## 2 tvolume     VAT1L VAF1L DXSSD      2.76 0.00603 0.0500    -0.268
## 3 pvertex     R_ce… VAF3L DXSSD      2.76 0.00602 0.0499    -0.268
## 4 tvolume     L_ce… FPP2R DXSSD     -2.76 0.00601 0.0499     0.268
## 5 tvolume     L_th… VI01L DXSSD      2.76 0.00600 0.0499    -0.268
## # … with 1 more variable: cohenD_DX_tstatdir &lt;dbl&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">saveRDS</span>(DX_lm_model_DXcohenD, <span class="dt">file =</span> <span class="kw">file.path</span>(output_base, <span class="st">&quot;all_clinicalplusqa_group&quot;</span>, <span class="st">&quot;Rdata_cache&quot;</span>, <span class="st">&quot;06_wholebrain_FC_DXlmfits.rds&quot;</span>))</code></pre></div>
<p>can get the model fit back from here..</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="dt">file =</span> <span class="kw">file.path</span>(output_base, <span class="st">&quot;all_clinicalplusqa_group&quot;</span>, <span class="st">&quot;Rdata_cache&quot;</span>, <span class="st">&quot;06_wholebrain_FC_DXlmfits.rds&quot;</span>))</code></pre></div>
</div>
<div id="make-co" class="section level2">
<h2><span class="header-section-number">9.4</span> Make co</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&#39;code/R/swirly_plot_helpers.R&#39;</span>))
DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span>## filtering steps
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span>
<span class="st">  </span>## make a pretty plot
<span class="st">  </span><span class="kw">make_swirly_results_plot</span>(<span class="dt">pos_label =</span> <span class="st">&quot;SSD &gt; HC&quot;</span>, 
                      <span class="dt">neg_label =</span> <span class="st">&quot;HC &gt; SSD&quot;</span>,
                      <span class="dt">plot_title =</span> <span class="st">&quot;Personalized&quot;</span>,
                      <span class="dt">node_annotations =</span> node_annotations)</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-16-1.png" width="960" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">make_swirly_results_plot</span>(<span class="dt">pos_label =</span> <span class="st">&quot;SSD &gt; HC&quot;</span>, 
                      <span class="dt">neg_label =</span> <span class="st">&quot;HC &gt; SSD&quot;</span>,
                      <span class="dt">plot_title =</span> <span class="st">&quot;Template&quot;</span>,
                      <span class="dt">node_annotations =</span> node_annotations)</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-17-1.png" width="960" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvolume&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">make_swirly_results_plot</span>(<span class="dt">pos_label =</span> <span class="st">&quot;SSD &gt; HC&quot;</span>, 
                      <span class="dt">neg_label =</span> <span class="st">&quot;HC &gt; SSD&quot;</span>,
                      <span class="dt">plot_title =</span> <span class="st">&quot;Volume&quot;</span>,
                      <span class="dt">node_annotations =</span> node_annotations)</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-18-1.png" width="960" /></p>
</div>
<div id="make-table-fdr-corrected-edges-that-survive-correction" class="section level2">
<h2><span class="header-section-number">9.5</span> make table FDR corrected Edges that survive correction</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(annotated_graph_edges, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>, <span class="st">&quot;from&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sig_edge =</span> <span class="kw">if_else</span>(p_FDR <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>, <span class="st">&quot;sig&quot;</span>, <span class="st">&quot;ns&quot;</span>),
         <span class="dt">stat_pos =</span> <span class="kw">if_else</span>(statistic <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;pos&quot;</span>, <span class="st">&quot;neg&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">count</span>(vertex_type, from_to_type, sig_edge) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sig_edge, n) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">perc_sig =</span> sig<span class="op">/</span>(ns <span class="op">+</span><span class="st"> </span>sig)<span class="op">*</span><span class="dv">100</span>)</code></pre></div>
<pre><code>## # A tibble: 9 x 6
## # Groups:   term [1]
##   term  vertex_type from_to_type       ns   sig perc_sig
##   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;           &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;
## 1 DXSSD pvertex     Cort_Cort        2956   204     6.46
## 2 DXSSD pvertex     SubCort_Cort     2760   440    13.8 
## 3 DXSSD pvertex     SubCort_SubCort   249   284    53.3 
## 4 DXSSD tvertex     Cort_Cort        2952   208     6.58
## 5 DXSSD tvertex     SubCort_Cort     2829   371    11.6 
## 6 DXSSD tvertex     SubCort_SubCort   249   284    53.3 
## 7 DXSSD tvolume     Cort_Cort        3018   142     4.49
## 8 DXSSD tvolume     SubCort_Cort     2923   277     8.66
## 9 DXSSD tvolume     SubCort_SubCort   249   284    53.3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_sig_edge_table &lt;-<span class="st"> </span>DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(annotated_graph_edges, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>, <span class="st">&quot;from&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sig_edge =</span> <span class="kw">if_else</span>(p_FDR <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>, <span class="st">&quot;sig&quot;</span>, <span class="st">&quot;ns&quot;</span>),
         <span class="dt">stat_pos =</span> <span class="kw">if_else</span>(statistic <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;pos&quot;</span>, <span class="st">&quot;neg&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, from_to_type <span class="op">!=</span><span class="st"> &quot;SubCort_SubCort&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">count</span>(vertex_type,  sig_edge) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sig_edge, n) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">perc_sig =</span> sig<span class="op">/</span>(ns <span class="op">+</span><span class="st"> </span>sig)<span class="op">*</span><span class="dv">100</span>)

DX_sig_edge_table</code></pre></div>
<pre><code>## # A tibble: 3 x 5
## # Groups:   term [1]
##   term  vertex_type    ns   sig perc_sig
##   &lt;chr&gt; &lt;chr&gt;       &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;
## 1 DXSSD pvertex      5716   644    10.1 
## 2 DXSSD tvertex      5781   579     9.10
## 3 DXSSD tvolume      5941   419     6.59</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">YeoNet7 &lt;-<span class="st"> </span><span class="kw">define_YeoNet7_colours</span>()
node_annotations1 &lt;-<span class="st"> </span>node_annotations <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">node_grouping  =</span> <span class="kw">if_else</span>(etype <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>,
                                  <span class="kw">str_c</span>(<span class="st">&quot;Cort&quot;</span>, cort_NET),
                                  <span class="kw">as.character</span>(subcort_ROI))) 

node_groupings &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>, 
                         <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>),
                         <span class="dt">labels =</span> <span class="kw">c</span>(<span class="kw">levels</span>(node_annotations<span class="op">$</span>subcort_ROI),
                                    <span class="kw">str_c</span>(<span class="st">&quot;Cort&quot;</span>,YeoNet7<span class="op">$</span>network[<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>])))
edge_grouping_guide &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span>, 
                  <span class="dt">nrow =</span> <span class="kw">length</span>(node_groupings),
                  <span class="dt">ncol =</span> <span class="kw">length</span>(node_groupings),
                  <span class="dt">dimnames =</span> <span class="kw">list</span>(node_groupings,
                                  node_groupings)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">graph_from_adjacency_matrix</span>(<span class="dt">mode=</span><span class="st">&quot;upper&quot;</span>, 
                                <span class="dt">weighted=</span>T, <span class="dt">diag=</span>T) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">as_data_frame</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span>(from <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;striatum&quot;</span>, <span class="st">&quot;thalamus&quot;</span>, <span class="st">&quot;cerebellum&quot;</span>) <span class="op">&amp;</span><span class="st"> </span>to <span class="op">==</span><span class="st"> </span>from)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(to, from)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations1, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations1, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">mutate</span>(<span class="dt">sig_edge =</span> <span class="kw">if_else</span>(p_FDR <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>, <span class="st">&quot;sig&quot;</span>, <span class="st">&quot;ns&quot;</span>),
      <span class="dt">stat_pos =</span> <span class="kw">if_else</span>(statistic <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;pos&quot;</span>, <span class="st">&quot;neg&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">      </span><span class="kw">count</span>(vertex_type, node_grouping.x, node_grouping.y, stat_pos, sig_edge) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">group_by</span>(vertex_type, node_grouping.x, node_grouping.y, stat_pos) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">spread</span>(sig_edge, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">mutate</span>(<span class="dt">sig_signed =</span> <span class="kw">if_else</span>(stat_pos <span class="op">==</span><span class="st"> &quot;pos&quot;</span>, sig, sig<span class="op">*-</span><span class="dv">1</span>),
             <span class="dt">node_grouping_x =</span> <span class="kw">factor</span>(node_grouping.x, <span class="dt">levels =</span> node_groupings),
             <span class="dt">node_grouping_y =</span> <span class="kw">factor</span>(node_grouping.y, <span class="dt">levels =</span> node_groupings)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">mutate</span>(<span class="dt">node_grouping_fx =</span> <span class="kw">if_else</span>(node_grouping_x <span class="op">==</span><span class="st"> &quot;CortDA&quot;</span> <span class="op">&amp;</span><span class="st"> </span>node_grouping_y <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;CortVA&quot;</span>, <span class="st">&quot;CortFP&quot;</span>, <span class="st">&quot;CortDM&quot;</span>), 
                                        node_grouping_y, node_grouping_x),
             <span class="dt">node_grouping_fy =</span> <span class="kw">if_else</span>(node_grouping_x <span class="op">==</span><span class="st"> &quot;CortDA&quot;</span> <span class="op">&amp;</span><span class="st"> </span>node_grouping_y <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;CortVA&quot;</span>, <span class="st">&quot;CortFP&quot;</span>, <span class="st">&quot;CortDM&quot;</span>), 
                                        node_grouping_x, node_grouping_y)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> node_grouping_fx, <span class="dt">y =</span> node_grouping_fy, <span class="dt">fill =</span> sig_signed)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_tile</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> sig)) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_distiller</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>,<span class="fl">0.5</span>), <span class="dt">type =</span> <span class="st">&quot;div&quot;</span>, <span class="dt">palette =</span> <span class="dv">5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_grid</span>(vertex_type <span class="op">~</span><span class="st"> </span>stat_pos)</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-22-1.png" width="576" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#&#39; convert from three col graph df to adjacency matrix</span>
uppertri_df_to_agjmat &lt;-<span class="st"> </span><span class="cf">function</span>(graph_df) {
  
<span class="kw">names</span>(graph_df) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;to&#39;</span>, <span class="st">&#39;from&#39;</span>, <span class="st">&#39;myattr&#39;</span>)
matrix_out &lt;-<span class="st"> </span>graph_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">graph_from_data_frame</span>(.,<span class="dt">directed =</span> F) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">get.adjacency</span>(., <span class="dt">type =</span> <span class="st">&quot;both&quot;</span>, <span class="dt">attr =</span> <span class="st">&quot;myattr&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">as.matrix</span>() 
<span class="kw">return</span>(matrix_out)
}

<span class="co">#&#39; go uppertri data to full dataframe for geom_tile</span>
uppertri_df_to_full &lt;-<span class="st"> </span><span class="cf">function</span>(graph_df) {
result &lt;-<span class="st"> </span>graph_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">uppertri_df_to_agjmat</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">as.data.frame</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">to =</span> <span class="kw">row.names</span>(.)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(from, value, <span class="op">-</span>to) 
<span class="kw">return</span>(result)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_filtered =</span> <span class="kw">if_else</span>(p_FDR <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.1</span>, statistic, <span class="dv">0</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(vertex_type, to, from, t_filtered) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(vertex_type) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">uptri =</span> <span class="kw">map</span>(data, uppertri_df_to_full)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest</span>(uptri) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">to_lab =</span> <span class="kw">factor</span>(to, <span class="dt">levels =</span> (node_annotations <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(subcort_ROI, network))<span class="op">$</span>node_name),
         <span class="dt">from_lab =</span> <span class="kw">factor</span>(from, <span class="dt">levels =</span> (node_annotations <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(subcort_ROI, network))<span class="op">$</span>node_name)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>to_lab, <span class="dt">y=</span>from_lab, <span class="dt">fill=</span>value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_tile</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">high =</span> <span class="st">&quot;#b2182b&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">low =</span> <span class="st">&quot;#2166ac&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>vertex_type, <span class="dt">ncol =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;T statistic for effect of DX (thesholded)&quot;</span>,
       <span class="dt">x =</span> <span class="ot">NULL</span>, <span class="dt">y =</span> <span class="ot">NULL</span>, <span class="dt">fill =</span> <span class="st">&quot;T statistic for DX&quot;</span>)</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-24-1.png" width="1152" /></p>
<p>`</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">full_DX_mat &lt;-<span class="st"> </span>DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(to, from, statistic) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">uppertri_df_to_full</span>() 

full_DX_mat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">to_lab =</span> <span class="kw">factor</span>(to, <span class="dt">levels =</span> node_annotations<span class="op">$</span>node_name), 
         <span class="dt">from_lab =</span> <span class="kw">factor</span>(from, <span class="dt">levels =</span> node_annotations<span class="op">$</span>node_name)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>to_lab, <span class="dt">y=</span>from_lab, <span class="dt">fill=</span>value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_tile</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">high =</span> <span class="st">&quot;#b2182b&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">low =</span> <span class="st">&quot;#2166ac&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;T statistic for effect of DX&quot;</span>,
       <span class="dt">x =</span> <span class="ot">NULL</span>, <span class="dt">y =</span> <span class="ot">NULL</span>, <span class="dt">fill =</span> <span class="st">&quot;T statistic for DX&quot;</span>)</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-25-1.png" width="1152" /> ### trying to plot edges in subgroups</p>
<p>Plotting Subcortical to Cortical Edges</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggridges)

make_subcortcort_edges_raincloud &lt;-<span class="st"> </span><span class="cf">function</span>(data,D_threshold) {

get_subcort_net_edges &lt;-<span class="st"> </span><span class="cf">function</span>(data, this_YeoNet, D_threshold) {
      data <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">select</span>(to, from, cohenD_DX_tstatdir) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">uppertri_df_to_full</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;SubCort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>)
      
}

DXweigths_pvertex &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">get_subcort_net_edges</span>(.,this_YeoNet) 

DXweigths_tvertex &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;tvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">get_subcort_net_edges</span>(.,this_YeoNet)

DXweigths_tvolume &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;tvolume&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">get_subcort_net_edges</span>(.,this_YeoNet)

Fz_DXweigths &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="dt">pvertex =</span> DXweigths_pvertex,
                     <span class="dt">tvertex =</span> DXweigths_tvertex,
                     <span class="dt">tvolume =</span> DXweigths_tvolume,
                     <span class="dt">.id =</span> <span class="st">&quot;vertex_type&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">mutate</span>(<span class="dt">corrtype =</span> <span class="kw">factor</span>(vertex_type, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&#39;pvertex&#39;</span>, <span class="st">&#39;tvertex&#39;</span>, <span class="st">&#39;tvolume&#39;</span>),
                             <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Surface Personalized&quot;</span>, 
                                        <span class="st">&quot;Surface Template&quot;</span>, 
                                        <span class="st">&quot;Volume Template&quot;</span>)),
           <span class="dt">hyper_hypo =</span> <span class="kw">case_when</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>D_threshold <span class="op">~</span><span class="st"> &quot;hypo&quot;</span>,
                                  value <span class="op">&gt;</span><span class="st"> </span>D_threshold <span class="op">~</span><span class="st"> &quot;hyper&quot;</span>,
                                  <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;notsig&quot;</span>))

plt_counts &lt;-<span class="st"> </span>Fz_DXweigths <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(corrtype, network.y, hyper_hypo) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(hyper_hypo, n, <span class="dt">fill =</span> <span class="dv">0</span>)


make_one_net_ridgelines &lt;-<span class="st"> </span><span class="cf">function</span>(plt_data, plt_counts, this_YeoNet, D_threshold, <span class="dt">no_ticks =</span> <span class="ot">TRUE</span>) {
    plt &lt;-<span class="st"> </span>plt_data <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(this_YeoNet)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">x =</span> value)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_density_ridges</span>(
      <span class="co">#jittered_points = TRUE, position = &quot;raincloud&quot;,</span>
      <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">scale =</span> <span class="dv">2</span>,
      <span class="dt">quantile_lines =</span> <span class="ot">TRUE</span>, <span class="dt">quantiles =</span> <span class="dv">2</span>,
      <span class="dt">color =</span> YeoNet7 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(network<span class="op">==</span>this_YeoNet) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(hexcode)
    ) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">label =</span> hyper), 
          <span class="dt">x =</span> <span class="fl">0.5</span>, 
          <span class="dt">nudge_y =</span> <span class="fl">0.2</span>, <span class="dt">data =</span> plt_counts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(this_YeoNet))) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">label =</span> hypo), 
          <span class="dt">x =</span> <span class="op">-</span><span class="fl">0.5</span>, 
          <span class="dt">nudge_y =</span> <span class="fl">0.2</span>, <span class="dt">data =</span> plt_counts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(this_YeoNet))) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> D_threshold, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="op">-</span>D_threshold, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_colour_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(YeoNet7 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(network<span class="op">==</span>this_YeoNet) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(hexcode))) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.6</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="ot">NULL</span>,
         <span class="dt">x =</span> <span class="ot">NULL</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&#39;none&#39;</span>)

<span class="cf">if</span> (no_ticks<span class="op">==</span><span class="ot">TRUE</span>) {
    plt &lt;-<span class="st"> </span>plt <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.title.x=</span><span class="kw">element_blank</span>(),
                       <span class="dt">axis.text.x=</span><span class="kw">element_blank</span>())
  } <span class="cf">else</span> {
    plt &lt;-<span class="st"> </span>plt <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Subcortical to Cortical Edges&quot;</span>)
  }
  <span class="kw">return</span>(plt)
  
}


  DM &lt;-<span class="st"> </span><span class="kw">make_one_net_ridgelines</span>(Fz_DXweigths, plt_counts, <span class="st">&quot;DM&quot;</span>, D_threshold)
  FP &lt;-<span class="st"> </span><span class="kw">make_one_net_ridgelines</span>(Fz_DXweigths, plt_counts, <span class="st">&quot;FP&quot;</span>, D_threshold)
  VA &lt;-<span class="st"> </span><span class="kw">make_one_net_ridgelines</span>(Fz_DXweigths, plt_counts, <span class="st">&quot;VA&quot;</span>, D_threshold)
  DA &lt;-<span class="st"> </span><span class="kw">make_one_net_ridgelines</span>(Fz_DXweigths, plt_counts, <span class="st">&quot;DA&quot;</span>, D_threshold)
  SM &lt;-<span class="st"> </span><span class="kw">make_one_net_ridgelines</span>(Fz_DXweigths, plt_counts, <span class="st">&quot;SM&quot;</span>, D_threshold)
  VI &lt;-<span class="st"> </span><span class="kw">make_one_net_ridgelines</span>(Fz_DXweigths, plt_counts, <span class="st">&quot;VI&quot;</span>, D_threshold, <span class="dt">no_ticks =</span> <span class="ot">FALSE</span>)

  title &lt;-<span class="st"> </span><span class="kw">ggdraw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">draw_label</span>(<span class="st">&quot;Subcortical to Cortical&quot;</span>, <span class="dt">fontface=</span><span class="st">&#39;bold&#39;</span>)
  full_plt &lt;-<span class="st"> </span><span class="kw">plot_grid</span>(title, DM, FP, VA, DA, SM, VI,
                   <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">rel_heights =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="fl">1.5</span>))
  <span class="kw">return</span>(full_plt)
}


<span class="kw">make_subcortcort_edges_raincloud</span>(DX_lm_model_DXcohenD,<span class="dt">D_threshold =</span> <span class="fl">0.2678</span>)</code></pre></div>
<pre><code>## Picking joint bandwidth of 0.0335</code></pre>
<pre><code>## Picking joint bandwidth of 0.0277</code></pre>
<pre><code>## Picking joint bandwidth of 0.0346</code></pre>
<pre><code>## Picking joint bandwidth of 0.0324</code></pre>
<pre><code>## Picking joint bandwidth of 0.0376</code></pre>
<pre><code>## Picking joint bandwidth of 0.0308</code></pre>
<pre><code>## Warning: Removed 4 rows containing non-finite values (stat_density_ridges).</code></pre>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-26-1.png" width="480" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggridges)

make_cortcort_edges_raincloud &lt;-<span class="st"> </span><span class="cf">function</span>(data,D_threshold) {

get_cortcort_net_edges &lt;-<span class="st"> </span><span class="cf">function</span>(data) {
      data <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">select</span>(to, from, cohenD_DX_tstatdir) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">uppertri_df_to_full</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>)
      
}

DXweigths_pvertex &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">get_cortcort_net_edges</span>() 

DXweigths_tvertex &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;tvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">get_cortcort_net_edges</span>()

DXweigths_tvolume &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;tvolume&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">get_cortcort_net_edges</span>()

Fz_DXweigths &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="dt">pvertex =</span> DXweigths_pvertex,
                     <span class="dt">tvertex =</span> DXweigths_tvertex,
                     <span class="dt">tvolume =</span> DXweigths_tvolume,
                     <span class="dt">.id =</span> <span class="st">&quot;vertex_type&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">mutate</span>(<span class="dt">corrtype =</span> <span class="kw">factor</span>(vertex_type, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&#39;pvertex&#39;</span>, <span class="st">&#39;tvertex&#39;</span>, <span class="st">&#39;tvolume&#39;</span>),
                             <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Surface Personalized&quot;</span>, 
                                        <span class="st">&quot;Surface Template&quot;</span>, 
                                        <span class="st">&quot;Volume Template&quot;</span>)),
           <span class="dt">hyper_hypo =</span> <span class="kw">case_when</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>D_threshold <span class="op">~</span><span class="st"> &quot;hypo&quot;</span>,
                                  value <span class="op">&gt;</span><span class="st"> </span>D_threshold <span class="op">~</span><span class="st"> &quot;hyper&quot;</span>,
                                  <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;notsig&quot;</span>))

all_plt_counts &lt;-<span class="st"> </span>Fz_DXweigths <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(corrtype, network.y, network.x, hyper_hypo) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(hyper_hypo, n, <span class="dt">fill =</span> <span class="dv">0</span>)


make_two_net_ridgelines &lt;-<span class="st"> </span><span class="cf">function</span>(plt_data, all_plt_counts, network_x, network_y, D_threshold, <span class="dt">no_ticks =</span> <span class="ot">TRUE</span>) {
    plt_counts &lt;-<span class="st"> </span>all_plt_counts <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x)<span class="op">==</span><span class="st"> </span>network_x,
           <span class="kw">as.character</span>(network.y)<span class="op">==</span><span class="st"> </span>network_y,)
  
    plt &lt;-<span class="st"> </span>plt_data <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x)<span class="op">==</span><span class="st"> </span>network_x,
           <span class="kw">as.character</span>(network.y)<span class="op">==</span><span class="st"> </span>network_y,) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">x =</span> value)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_density_ridges</span>(
      <span class="co">#jittered_points = TRUE, position = &quot;raincloud&quot;,</span>
      <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">scale =</span> <span class="dv">2</span>,
      <span class="dt">quantile_lines =</span> <span class="ot">TRUE</span>, <span class="dt">quantiles =</span> <span class="dv">2</span>,
      <span class="dt">color =</span> YeoNet7 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(network<span class="op">==</span>network_x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(hexcode),
      <span class="dt">fill =</span> YeoNet7 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(network<span class="op">==</span>network_y) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(hexcode)
    ) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">label =</span> hyper), 
          <span class="dt">x =</span> <span class="fl">0.5</span>, 
          <span class="dt">nudge_y =</span> <span class="fl">0.2</span>, <span class="dt">data =</span> plt_counts) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">label =</span> hypo), 
          <span class="dt">x =</span> <span class="op">-</span><span class="fl">0.5</span>, 
          <span class="dt">nudge_y =</span> <span class="fl">0.2</span>, <span class="dt">data =</span> plt_counts) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> D_threshold, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="op">-</span>D_threshold, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.6</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="ot">NULL</span>,
         <span class="dt">x =</span> <span class="ot">NULL</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&#39;none&#39;</span>)

<span class="cf">if</span> (no_ticks<span class="op">==</span><span class="ot">TRUE</span>) {
    plt &lt;-<span class="st"> </span>plt <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.title.x=</span><span class="kw">element_blank</span>(),
                       <span class="dt">axis.text.x=</span><span class="kw">element_blank</span>())
  } <span class="cf">else</span> {
    plt &lt;-<span class="st"> </span>plt <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Cortical to Cortical Edges&quot;</span>)
  }
  <span class="kw">return</span>(plt)
  
}

  DM_DA &lt;-<span class="st"> </span><span class="kw">make_two_net_ridgelines</span>(Fz_DXweigths, all_plt_counts, <span class="st">&quot;DM&quot;</span>, <span class="st">&quot;DA&quot;</span>, D_threshold)
  DM_VA &lt;-<span class="st"> </span><span class="kw">make_two_net_ridgelines</span>(Fz_DXweigths, all_plt_counts, <span class="st">&quot;DM&quot;</span>, <span class="st">&quot;VA&quot;</span>, D_threshold)
  DM_SM &lt;-<span class="st"> </span><span class="kw">make_two_net_ridgelines</span>(Fz_DXweigths, all_plt_counts, <span class="st">&quot;DM&quot;</span>, <span class="st">&quot;SM&quot;</span>, D_threshold)
  FP_SM &lt;-<span class="st"> </span><span class="kw">make_two_net_ridgelines</span>(Fz_DXweigths, all_plt_counts, <span class="st">&quot;FP&quot;</span>, <span class="st">&quot;SM&quot;</span>, D_threshold)
  VA_DA &lt;-<span class="st"> </span><span class="kw">make_two_net_ridgelines</span>(Fz_DXweigths, all_plt_counts, <span class="st">&quot;DA&quot;</span>, <span class="st">&quot;VA&quot;</span>, D_threshold)
  DA_SM &lt;-<span class="st"> </span><span class="kw">make_two_net_ridgelines</span>(Fz_DXweigths, all_plt_counts, <span class="st">&quot;DA&quot;</span>, <span class="st">&quot;SM&quot;</span>, D_threshold)
  VI_VI &lt;-<span class="st"> </span><span class="kw">make_two_net_ridgelines</span>(Fz_DXweigths, all_plt_counts, <span class="st">&quot;VI&quot;</span>, <span class="st">&quot;VI&quot;</span>, D_threshold, <span class="dt">no_ticks =</span> <span class="ot">FALSE</span>)

  title &lt;-<span class="st"> </span><span class="kw">ggdraw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">draw_label</span>(<span class="st">&quot;Subcortical to Cortical&quot;</span>, <span class="dt">fontface=</span><span class="st">&#39;bold&#39;</span>)
  full_plt &lt;-<span class="st"> </span><span class="kw">plot_grid</span>(title, DM_DA, DM_VA, FP_SM, VA_DA, DA_SM, VI_VI,
                   <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">rel_heights =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>,  <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>,<span class="fl">1.5</span>))
  <span class="kw">return</span>(full_plt)
}


<span class="kw">make_cortcort_edges_raincloud</span>(DX_lm_model_DXcohenD,<span class="dt">D_threshold =</span> <span class="fl">0.2678</span>)</code></pre></div>
<pre><code>## Picking joint bandwidth of 0.0307</code></pre>
<pre><code>## Picking joint bandwidth of 0.0297</code></pre>
<pre><code>## Picking joint bandwidth of 0.0366</code></pre>
<pre><code>## Picking joint bandwidth of 0.031</code></pre>
<pre><code>## Picking joint bandwidth of 0.0329</code></pre>
<pre><code>## Picking joint bandwidth of 0.0497</code></pre>
<pre><code>## Warning: Removed 2 rows containing non-finite values (stat_density_ridges).</code></pre>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-27-1.png" width="480" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">D_threshold =<span class="st"> </span><span class="fl">0.2678</span>
hypo_cerebullum_to &lt;-<span class="st"> </span>DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">select</span>(to, from, cohenD_DX_tstatdir) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">uppertri_df_to_full</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">filter</span>(subcort_ROI.x <span class="op">==</span><span class="st"> &quot;cerebellum&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(subcort_ROI.y <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;striatum&quot;</span>, <span class="st">&quot;thalamus&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">hyper_hypo =</span> <span class="kw">case_when</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>D_threshold <span class="op">~</span><span class="st"> &quot;hypo&quot;</span>,
                                  value <span class="op">&gt;</span><span class="st"> </span>D_threshold <span class="op">~</span><span class="st"> &quot;hyper&quot;</span>,
                                  <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;notsig&quot;</span>),
           <span class="dt">corrtype =</span> <span class="kw">str_c</span>(subcort_ROI.y, <span class="st">&quot; to cerebellum&quot;</span>))

plt_counts &lt;-<span class="st"> </span>hypo_cerebullum_to <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(corrtype, hyper_hypo) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(hyper_hypo, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hyper =</span> <span class="dv">0</span>) <span class="co"># note this only works because there is no hyper</span>

hypo_cerebullum_to <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">x =</span> value)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_density_ridges</span>(
      <span class="co">#jittered_points = TRUE, position = &quot;raincloud&quot;,</span>
      <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">scale =</span> <span class="fl">1.5</span>,
      <span class="dt">quantile_lines =</span> <span class="ot">TRUE</span>, <span class="dt">quantiles =</span> <span class="dv">2</span>
    ) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">label =</span> hyper), 
          <span class="dt">x =</span> <span class="fl">0.5</span>, 
          <span class="dt">nudge_y =</span> <span class="fl">0.2</span>, <span class="dt">data =</span> plt_counts) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> corrtype, <span class="dt">label =</span> hypo), 
          <span class="dt">x =</span> <span class="op">-</span><span class="fl">2.5</span>, 
          <span class="dt">nudge_y =</span> <span class="fl">0.2</span>, <span class="dt">data =</span> plt_counts) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> D_threshold, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="op">-</span>D_threshold, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="ot">NULL</span>,
         <span class="dt">x =</span> <span class="ot">NULL</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&#39;none&#39;</span>)</code></pre></div>
<pre><code>## Picking joint bandwidth of 0.121</code></pre>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-28-1.png" width="480" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">calc_fc_weights &lt;-<span class="st"> </span><span class="cf">function</span>(lm_df, t_threshold) {
  
    full_DX_mat &lt;-<span class="st"> </span>lm_df <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">select</span>(to, from, cohenD_DX_tstatdir) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">uppertri_df_to_full</span>() <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">      </span><span class="kw">inner_join</span>(node_annotations, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;from&quot;</span>=<span class="st">&quot;node_name&quot;</span>)) 
    
hypo_cerebullum_to_striatum &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(subcort_ROI.x <span class="op">==</span><span class="st"> &quot;cerebellum&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(subcort_ROI.y <span class="op">==</span><span class="st"> &quot;striatum&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value) 

hypo_cerebullum_to_thalamus &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(subcort_ROI.x <span class="op">==</span><span class="st"> &quot;cerebellum&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(subcort_ROI.y <span class="op">==</span><span class="st"> &quot;thalamus&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hyper_subcort_to_SM &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;SubCort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;SM&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&gt;</span><span class="st"> </span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hyper_subcort_to_VI &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;SubCort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;VI&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&gt;</span><span class="st"> </span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hyper_subcort_to_DA &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;SubCort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DA&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&gt;</span><span class="st"> </span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hyper_subcort_to_DM &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;SubCort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DM&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&gt;</span><span class="st"> </span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hypo_subcort_to_FP &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;SubCort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;FP&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hypo_subcort_to_VA &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;SubCort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;VA&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hyper_cortDA_to_SM &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DA&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;SM&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&gt;</span><span class="st"> </span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hyper_cortVA_to_DA &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;VA&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DA&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&gt;</span><span class="st"> </span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hyper_cortFP_to_SM &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;FP&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;SM&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&gt;</span><span class="st"> </span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hypo_cortDM_to_DA &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DM&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DA&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hypo_cortDM_to_VA &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DM&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;VA&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

hypo_cortVI_to_VI &lt;-<span class="st"> </span>full_DX_mat <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.x <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(etype.y <span class="op">==</span><span class="st"> &quot;Cort&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.x) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;VI&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(<span class="kw">as.character</span>(network.y) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;VI&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(value <span class="op">&lt;</span><span class="st"> </span><span class="op">-</span>t_threshold) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(to, from, value)

Fz_weigths &lt;-<span class="kw">bind_rows</span>(<span class="dt">hyper_cortDA_to_SM =</span> hyper_cortDA_to_SM,
                       <span class="dt">hyper_cortFP_to_SM =</span> hyper_cortFP_to_SM,
                       <span class="dt">hyper_cortVA_to_DA =</span> hyper_cortVA_to_DA,
                       <span class="dt">hypo_cortDM_to_DA =</span> hypo_cortDM_to_DA,
                       <span class="dt">hypo_cortDM_to_VA =</span> hypo_cortDM_to_VA,
                       <span class="dt">hypo_cortVI_to_VI =</span> hypo_cortVI_to_VI,
                       <span class="dt">hyper_subcort_to_DM =</span> hyper_subcort_to_DM,
                       <span class="dt">hypo_subcort_to_FP =</span> hypo_subcort_to_FP,
                       <span class="dt">hypo_subcort_to_VA =</span> hypo_subcort_to_VA,
                       <span class="dt">hyper_subcort_to_DA =</span> hyper_subcort_to_DA,
                       <span class="dt">hyper_subcort_to_SM =</span> hyper_subcort_to_SM,
                       <span class="dt">hyper_subcort_to_VI =</span> hyper_subcort_to_VI,
                       <span class="dt">hypo_cerebullum_to_striatum =</span> hypo_cerebullum_to_striatum,
                       <span class="dt">hypo_cerebullum_to_thalamus =</span> hypo_cerebullum_to_thalamus,
                       <span class="dt">.id =</span> <span class="st">&quot;direction_edge_group&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">separate</span>(direction_edge_group, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;effect_direction&quot;</span>, <span class="st">&quot;edge_group&quot;</span>), <span class="dt">extra =</span> <span class="st">&quot;merge&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">edge_FC_weight =</span> value)

  <span class="kw">return</span>(Fz_weigths)

}</code></pre></div>
<div id="calculated-extract-edge-weights-for-per-participant-scores" class="section level3">
<h3><span class="header-section-number">9.5.1</span> calculated extract edge weights for per participant scores</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cohenD_threshold =<span class="st"> </span><span class="fl">0.2678</span>
cohenD_thresname =<span class="st"> &quot;pFDR&quot;</span>

Fz_DXweigths_pvertex &lt;-<span class="st"> </span>DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">calc_fc_weights</span>(.,cohenD_threshold)

Fz_DXweigths_tvertex &lt;-<span class="st"> </span>DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;tvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">calc_fc_weights</span>(.,cohenD_threshold)

Fz_DXweigths_tvolume &lt;-<span class="st"> </span>DX_lm_model_DXcohenD <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;tvolume&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">calc_fc_weights</span>(.,cohenD_threshold)

Fz_DXweigths &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="dt">pvertex =</span> Fz_DXweigths_pvertex,
                     <span class="dt">tvertex =</span> Fz_DXweigths_tvertex,
                     <span class="dt">tvolume =</span> Fz_DXweigths_tvolume,
                     <span class="dt">.id =</span> <span class="st">&quot;vertex_type&quot;</span>) 

<span class="kw">write_csv</span>(Fz_DXweigths, <span class="kw">file.path</span>(output_base, 
                                  <span class="st">&quot;all_clinicalplusqa_group&quot;</span>, 
                                  <span class="st">&quot;weighted_subject_FC_weigths&quot;</span>,
                                  <span class="kw">str_c</span>(<span class="st">&quot;SSD4cohorts_DXtweigths_&quot;</span>, 
                                        cohenD_thresname, <span class="st">&quot;.csv&quot;</span>)))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Fz_DXweigths <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">count</span>(edge_group, vertex_type, effect_direction) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(vertex_type, n)</code></pre></div>
<pre><code>##                edge_group effect_direction pvertex tvertex tvolume
## 1  cerebullum_to_striatum             hypo      86      86      86
## 2  cerebullum_to_thalamus             hypo     131     131     131
## 3            cortDA_to_SM            hyper      30      19      13
## 4            cortDM_to_DA             hypo      32      15      NA
## 5            cortDM_to_VA             hypo      23      21       4
## 6            cortFP_to_SM            hyper       9      12      10
## 7            cortVA_to_DA            hyper      23      33      30
## 8            cortVI_to_VI             hypo      48      30       8
## 9           subcort_to_DA            hyper      25      34      24
## 10          subcort_to_DM            hyper      44      14      10
## 11          subcort_to_FP             hypo      29      33      21
## 12          subcort_to_SM            hyper     101      93      78
## 13          subcort_to_VA             hypo      26      24      28
## 14          subcort_to_VI            hyper     194     133      75</code></pre>
</div>
<div id="calculated-scores-per-participant" class="section level3">
<h3><span class="header-section-number">9.5.2</span> calculated scores per participant</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#&#39; calculates a subjects weigthed FC score from their edgewise values</span>
<span class="co">#&#39;</span>
<span class="co">#&#39; @param subject_edges_df tibble with columns subject, to, from, and weight</span>
<span class="co">#&#39; @param edge_weights tibble with columns effect_direction, edge_group, to, from, and edge_FC_weight</span>
<span class="co">#&#39;</span>
<span class="co">#&#39; @return tibble with columns subject, dataset, effect_direction, edge_group, FC_subtype and wFC_score</span>
<span class="co">#&#39;</span>
<span class="co">#&#39; @examples</span>
calc_subjects_wFC_score &lt;-<span class="st"> </span><span class="cf">function</span>(subject_edges_df, edge_weights) {
  result &lt;-<span class="st"> </span>subject_edges_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(subject, dataset) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">uptri =</span> <span class="kw">map</span>(data, uppertri_df_to_full)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest</span>(uptri) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(edge_weights, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;to&quot;</span>, <span class="st">&quot;from&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(subject, dataset, effect_direction, edge_group) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">wFC_score =</span> <span class="kw">weighted.mean</span>(value, <span class="dt">w =</span> edge_FC_weight),
            <span class="dt">mFC_score =</span> <span class="kw">mean</span>(value)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>()
  <span class="kw">return</span>(result)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvertex_subject_FC_scores &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subject, dataset, to, from, weight) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">calc_subjects_wFC_score</span>(Fz_DXweigths_pvertex)</code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;subject&#39;, &#39;dataset&#39;, &#39;effect_direction&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tvertex_subject_FC_scores &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subject, dataset, to, from, weight) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">calc_subjects_wFC_score</span>(Fz_DXweigths_tvertex)</code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;subject&#39;, &#39;dataset&#39;, &#39;effect_direction&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tvolume_subject_FC_scores &lt;-<span class="st"> </span>results_pheno <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;tvolume&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subject, dataset, to, from, weight) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">calc_subjects_wFC_score</span>(Fz_DXweigths_tvolume)</code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;subject&#39;, &#39;dataset&#39;, &#39;effect_direction&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FC_scores_together &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(
  <span class="dt">pvertex =</span> pvertex_subject_FC_scores,
  <span class="dt">tvertex =</span> tvertex_subject_FC_scores,
  <span class="dt">tvolume =</span> tvolume_subject_FC_scores,
  <span class="dt">.id =</span> <span class="st">&quot;vertex_type&quot;</span>
)

<span class="kw">write_csv</span>(FC_scores_together, <span class="kw">file.path</span>(output_base, 
                                        <span class="st">&quot;all_clinicalplusqa_group&quot;</span>, 
                                        <span class="st">&quot;weighted_subject_FC_scores&quot;</span>,
                                        <span class="st">&quot;SSD4cohorts_DXweighted_subject_scores.csv&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DX_sig_edge_table <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(sig)</code></pre></div>
<pre><code>## [1] 644</code></pre>
</div>
</div>
<div id="write-up-to-this-point.." class="section level2">
<h2><span class="header-section-number">9.6</span> write up to this point..</h2>
<p>We observed robust patterns of dysconnectivity that were strengthened using a surface-based approach and PINT (Number of differing pairwise-correlations: volume: {419}, surface: {579}, PINT: {644}, FDR corrected). Moreover, patterns of dyscnnectivity became more interpretable in terms of individual resting state networks and cortical heirarchy (see Supplemental Figure 2 for breakdown by cortical network). Overall, regardless of cortical mapping approach, hypoconnectivity, that is decreased connectivity in participants with schizophrenia relative to controls as observed for edges connecting subcortical regions to the fronto-parietal network. Hyperconnectivity, or increased connectivity in participants with SSD relative to controls was observed for subcortical connections to those visual, somatomor, and dorsal attention networks, which increased when moving from volume-to-surface, and again from surface-to-PINT. Additional patterns of hypoconnectivity where observed between the cortical default-mode network and the dorsal and ventral attention netoworks, as well as within visual network edges. Cortical hyperconnectivity was observed between the dorsal and ventral attenetion networks, as well as the frontoparietal network to the somatomotor network. Moreover, hypoconnectivity was observed for nearly half of edges connecting the cerebellum to the striatum and the cerebellum to the thalamus.</p>
<p>To investigate these patterns further, sub-scored for these groups of edges were calculated to for each participants by taking the weighted-mean of all edges with that survived FDR corretion (Cohen's D threshold = {0.2678}, means were weighted by the SSD diagnosis effect size).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FC_scores_lmfit &lt;-<span class="st"> </span>FC_scores_together <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(pheno, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;dataset&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(edge_group, effect_direction, vertex_type) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="kw">tidy</span>(<span class="kw">lm</span>(wFC_score <span class="op">~</span><span class="st"> </span>DX <span class="op">+</span><span class="st"> </span>Age_pt <span class="op">+</span><span class="st"> </span>Sex <span class="op">+</span><span class="st"> </span>fd_mean_pt <span class="op">+</span><span class="st"> </span>Scanner,.))) 

FC_scores_lmfit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(edge_group, effect_direction, term, statistic, p.value) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<pre><code>## Adding missing grouping variables: `vertex_type`</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">vertex_type</th>
<th align="left">edge_group</th>
<th align="left">effect_direction</th>
<th align="left">term</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">pvertex</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.186413</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvertex</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.186413</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvolume</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.186413</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">pvertex</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-8.126418</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvertex</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-8.126418</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvolume</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-8.126418</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">pvertex</td>
<td align="left">cortDA_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">5.925091</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvertex</td>
<td align="left">cortDA_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">6.876098</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvolume</td>
<td align="left">cortDA_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">5.721400</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">pvertex</td>
<td align="left">cortDM_to_DA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-5.773509</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvertex</td>
<td align="left">cortDM_to_DA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.564210</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">pvertex</td>
<td align="left">cortDM_to_VA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-5.298831</td>
<td align="right">2.00e-07</td>
</tr>
<tr class="odd">
<td align="left">tvertex</td>
<td align="left">cortDM_to_VA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.852014</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvolume</td>
<td align="left">cortDM_to_VA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-5.362809</td>
<td align="right">1.00e-07</td>
</tr>
<tr class="odd">
<td align="left">pvertex</td>
<td align="left">cortFP_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">4.699304</td>
<td align="right">3.60e-06</td>
</tr>
<tr class="even">
<td align="left">tvertex</td>
<td align="left">cortFP_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">5.919053</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvolume</td>
<td align="left">cortFP_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">5.098214</td>
<td align="right">5.00e-07</td>
</tr>
<tr class="even">
<td align="left">pvertex</td>
<td align="left">cortVA_to_DA</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">5.480320</td>
<td align="right">1.00e-07</td>
</tr>
<tr class="odd">
<td align="left">tvertex</td>
<td align="left">cortVA_to_DA</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.651558</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvolume</td>
<td align="left">cortVA_to_DA</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">6.389303</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">pvertex</td>
<td align="left">cortVI_to_VI</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-5.483734</td>
<td align="right">1.00e-07</td>
</tr>
<tr class="even">
<td align="left">tvertex</td>
<td align="left">cortVI_to_VI</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.393396</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvolume</td>
<td align="left">cortVI_to_VI</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-4.216663</td>
<td align="right">3.07e-05</td>
</tr>
<tr class="even">
<td align="left">pvertex</td>
<td align="left">subcort_to_DA</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">5.273220</td>
<td align="right">2.00e-07</td>
</tr>
<tr class="odd">
<td align="left">tvertex</td>
<td align="left">subcort_to_DA</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.083454</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvolume</td>
<td align="left">subcort_to_DA</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.089347</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">pvertex</td>
<td align="left">subcort_to_DM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.142738</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvertex</td>
<td align="left">subcort_to_DM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">6.982997</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvolume</td>
<td align="left">subcort_to_DM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">6.298543</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">pvertex</td>
<td align="left">subcort_to_FP</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.772180</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvertex</td>
<td align="left">subcort_to_FP</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-7.289079</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvolume</td>
<td align="left">subcort_to_FP</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-7.321904</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">pvertex</td>
<td align="left">subcort_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">6.820810</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvertex</td>
<td align="left">subcort_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.841656</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvolume</td>
<td align="left">subcort_to_SM</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.641352</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">pvertex</td>
<td align="left">subcort_to_VA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-6.451742</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvertex</td>
<td align="left">subcort_to_VA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-7.155871</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvolume</td>
<td align="left">subcort_to_VA</td>
<td align="left">hypo</td>
<td align="left">DXSSD</td>
<td align="right">-8.220291</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">pvertex</td>
<td align="left">subcort_to_VI</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.338969</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">tvertex</td>
<td align="left">subcort_to_VI</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.818418</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">tvolume</td>
<td align="left">subcort_to_VI</td>
<td align="left">hyper</td>
<td align="left">DXSSD</td>
<td align="right">7.078653</td>
<td align="right">0.00e+00</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FC_scores_lmfit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(vertex_type, edge_group, effect_direction) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>,
         <span class="kw">str_detect</span>(edge_group,<span class="st">&quot;subcort&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="kw">abs</span>(statistic), <span class="dt">x =</span> <span class="kw">rev</span>(vertex_type), <span class="dt">color =</span> edge_group)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">group =</span> edge_group))</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FC_scores_lmfit &lt;-<span class="st"> </span>FC_scores_together <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(pheno, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;dataset&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(edge_group, vertex_type,  effect_direction, Site) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="kw">tidy</span>(<span class="kw">lm</span>(wFC_score <span class="op">~</span><span class="st"> </span>DX <span class="op">+</span><span class="st"> </span>Age_pt <span class="op">+</span><span class="st"> </span>Sex <span class="op">+</span><span class="st"> </span>fd_mean_pt,.))) 

FC_scores_lmfit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(edge_group, vertex_type, Site, term, statistic, p.value) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<pre><code>## Adding missing grouping variables: `effect_direction`</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">effect_direction</th>
<th align="left">edge_group</th>
<th align="left">vertex_type</th>
<th align="left">Site</th>
<th align="left">term</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.5738171</td>
<td align="right">0.0005370</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-1.8151375</td>
<td align="right">0.0763226</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.9588712</td>
<td align="right">0.0044903</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-3.4056876</td>
<td align="right">0.0008121</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.5738171</td>
<td align="right">0.0005370</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-1.8151375</td>
<td align="right">0.0763226</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.9588712</td>
<td align="right">0.0044903</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-3.4056876</td>
<td align="right">0.0008121</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.5738171</td>
<td align="right">0.0005370</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-1.8151375</td>
<td align="right">0.0763226</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.9588712</td>
<td align="right">0.0044903</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_striatum</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-3.4056876</td>
<td align="right">0.0008121</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6172504</td>
<td align="right">0.0000113</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.6686483</td>
<td align="right">0.0106237</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-4.7326351</td>
<td align="right">0.0000151</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6160245</td>
<td align="right">0.0000074</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6172504</td>
<td align="right">0.0000113</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.6686483</td>
<td align="right">0.0106237</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-4.7326351</td>
<td align="right">0.0000151</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6160245</td>
<td align="right">0.0000074</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6172504</td>
<td align="right">0.0000113</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.6686483</td>
<td align="right">0.0106237</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-4.7326351</td>
<td align="right">0.0000151</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cerebullum_to_thalamus</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6160245</td>
<td align="right">0.0000074</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.4605247</td>
<td align="right">0.0007858</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.5883789</td>
<td align="right">0.1193616</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">0.8064763</td>
<td align="right">0.4233205</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.9424312</td>
<td align="right">0.0000017</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.9659463</td>
<td align="right">0.0001352</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">0.7514483</td>
<td align="right">0.4563836</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.0769629</td>
<td align="right">0.2860339</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">6.0713815</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">1.6539474</td>
<td align="right">0.1011828</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.2962903</td>
<td align="right">0.2016335</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.8397476</td>
<td align="right">0.0710145</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortDA_to_SM</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.8696484</td>
<td align="right">0.0000024</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-2.2488685</td>
<td align="right">0.0266498</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-1.0690117</td>
<td align="right">0.2908942</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.5656064</td>
<td align="right">0.0129545</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6052396</td>
<td align="right">0.0000077</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.6694130</td>
<td align="right">0.0003870</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-1.6055266</td>
<td align="right">0.1155322</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.9133422</td>
<td align="right">0.0050995</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_DA</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.0026889</td>
<td align="right">0.0000911</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-1.5776234</td>
<td align="right">0.1177186</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.7644023</td>
<td align="right">0.0082990</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.6464987</td>
<td align="right">0.0104955</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-3.6651190</td>
<td align="right">0.0003242</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.2282384</td>
<td align="right">0.0016711</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.1184270</td>
<td align="right">0.0398222</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.2714493</td>
<td align="right">0.0269136</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-5.1196647</td>
<td align="right">0.0000008</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-2.6572843</td>
<td align="right">0.0091324</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-3.2498433</td>
<td align="right">0.0022164</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.3938342</td>
<td align="right">0.0199868</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortDM_to_VA</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-2.8874987</td>
<td align="right">0.0043538</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.2998736</td>
<td align="right">0.0013292</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">2.1723407</td>
<td align="right">0.0352600</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.1024222</td>
<td align="right">0.2749112</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">3.2467171</td>
<td align="right">0.0013898</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.0989110</td>
<td align="right">0.0025043</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">2.5247079</td>
<td align="right">0.0152600</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">2.1271389</td>
<td align="right">0.0377484</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">3.9391567</td>
<td align="right">0.0001164</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">2.4541891</td>
<td align="right">0.0157972</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.1820165</td>
<td align="right">0.2435480</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">3.5398854</td>
<td align="right">0.0008050</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortFP_to_SM</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">3.2232928</td>
<td align="right">0.0015019</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">1.2679338</td>
<td align="right">0.2076803</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.4393562</td>
<td align="right">0.1571264</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">4.6224661</td>
<td align="right">0.0000222</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.6879048</td>
<td align="right">0.0000054</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">2.4925742</td>
<td align="right">0.0142760</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.6653818</td>
<td align="right">0.1029422</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">2.7111927</td>
<td align="right">0.0088442</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">6.8510870</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">1.8850650</td>
<td align="right">0.0622396</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.7460976</td>
<td align="right">0.0877732</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">2.2095616</td>
<td align="right">0.0311682</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">cortVA_to_DA</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">5.5822563</td>
<td align="right">0.0000001</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-2.1605105</td>
<td align="right">0.0330516</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.7408364</td>
<td align="right">0.0088229</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-0.6228427</td>
<td align="right">0.5358720</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.2541813</td>
<td align="right">0.0000335</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.0887756</td>
<td align="right">0.0025837</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.0818537</td>
<td align="right">0.0432047</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-1.1142761</td>
<td align="right">0.2698372</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6517386</td>
<td align="right">0.0000063</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-1.9895495</td>
<td align="right">0.0492917</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.3873398</td>
<td align="right">0.0213328</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-1.3446992</td>
<td align="right">0.1840491</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">cortVI_to_VI</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-2.7534151</td>
<td align="right">0.0064958</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.3982361</td>
<td align="right">0.0009654</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.5352888</td>
<td align="right">0.1318731</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.2337519</td>
<td align="right">0.2223585</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">3.4420805</td>
<td align="right">0.0007161</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.5642111</td>
<td align="right">0.0005548</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">2.9049097</td>
<td align="right">0.0057281</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.9537523</td>
<td align="right">0.0556441</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.7147109</td>
<td align="right">0.0000048</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">4.6478503</td>
<td align="right">0.0000100</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">3.6634652</td>
<td align="right">0.0006651</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.6065518</td>
<td align="right">0.1136790</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DA</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.3301197</td>
<td align="right">0.0000246</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">2.4335530</td>
<td align="right">0.0166734</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">2.4001209</td>
<td align="right">0.0206874</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">4.0462588</td>
<td align="right">0.0001584</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">5.0852633</td>
<td align="right">0.0000009</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.7330010</td>
<td align="right">0.0003103</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">1.7385244</td>
<td align="right">0.0891124</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">2.8775910</td>
<td align="right">0.0056306</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.9203213</td>
<td align="right">0.0000019</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.1692934</td>
<td align="right">0.0020123</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">2.3938993</td>
<td align="right">0.0209993</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">4.3655518</td>
<td align="right">0.0000540</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_DM</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">3.1015981</td>
<td align="right">0.0022315</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.5016798</td>
<td align="right">0.0006850</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-3.0043103</td>
<td align="right">0.0043812</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-1.8414043</td>
<td align="right">0.0707679</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.4278006</td>
<td align="right">0.0000164</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.4612544</td>
<td align="right">0.0007839</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.6722293</td>
<td align="right">0.0105269</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-3.1792338</td>
<td align="right">0.0023876</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.7722615</td>
<td align="right">0.0000037</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-4.1782391</td>
<td align="right">0.0000617</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.2207510</td>
<td align="right">0.0315632</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-2.2644789</td>
<td align="right">0.0273656</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_FP</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.6832571</td>
<td align="right">0.0000055</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.7383364</td>
<td align="right">0.0003046</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">4.2077278</td>
<td align="right">0.0001250</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">2.5269281</td>
<td align="right">0.0143061</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">3.6518668</td>
<td align="right">0.0003402</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">4.3676777</td>
<td align="right">0.0000300</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">5.2941126</td>
<td align="right">0.0000036</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">3.0764450</td>
<td align="right">0.0032160</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.0931594</td>
<td align="right">0.0000639</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">4.0651540</td>
<td align="right">0.0000940</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">3.6926647</td>
<td align="right">0.0006095</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">3.8141038</td>
<td align="right">0.0003383</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_SM</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.3247986</td>
<td align="right">0.0000251</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-2.4042660</td>
<td align="right">0.0179912</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.9739368</td>
<td align="right">0.0047575</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-1.6334286</td>
<td align="right">0.1078912</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-4.8313921</td>
<td align="right">0.0000029</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-3.3339234</td>
<td align="right">0.0011908</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.4325199</td>
<td align="right">0.0191295</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-1.8442373</td>
<td align="right">0.0703477</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-5.3522347</td>
<td align="right">0.0000003</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">-4.0091401</td>
<td align="right">0.0001155</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">-2.0180347</td>
<td align="right">0.0497105</td>
</tr>
<tr class="odd">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">-3.2329145</td>
<td align="right">0.0020392</td>
</tr>
<tr class="even">
<td align="left">hypo</td>
<td align="left">subcort_to_VA</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">-6.0844455</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">pvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.2258252</td>
<td align="right">0.0016840</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">pvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">3.7500601</td>
<td align="right">0.0005129</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">pvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">2.3222757</td>
<td align="right">0.0238129</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">pvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.8046872</td>
<td align="right">0.0000032</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvertex</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">4.0500090</td>
<td align="right">0.0000994</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvertex</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">3.6023035</td>
<td align="right">0.0007979</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvertex</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.7488386</td>
<td align="right">0.0857023</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvertex</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">5.0786023</td>
<td align="right">0.0000009</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvolume</td>
<td align="left">CMH</td>
<td align="left">DXSSD</td>
<td align="right">3.7015792</td>
<td align="right">0.0003462</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvolume</td>
<td align="left">COBRE</td>
<td align="left">DXSSD</td>
<td align="right">3.7992718</td>
<td align="right">0.0004420</td>
</tr>
<tr class="odd">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvolume</td>
<td align="left">ds000030</td>
<td align="left">DXSSD</td>
<td align="right">1.8780589</td>
<td align="right">0.0654918</td>
</tr>
<tr class="even">
<td align="left">hyper</td>
<td align="left">subcort_to_VI</td>
<td align="left">tvolume</td>
<td align="left">ZHH</td>
<td align="left">DXSSD</td>
<td align="right">4.4637685</td>
<td align="right">0.0000141</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FC_scores_lmfit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;DXSSD&quot;</span>,
         <span class="kw">str_detect</span>(edge_group,<span class="st">&quot;subcort&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="kw">abs</span>(statistic), <span class="dt">x =</span> <span class="kw">rev</span>(vertex_type), <span class="dt">color =</span> edge_group)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">group =</span> edge_group)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>Site, <span class="dt">nrow =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SSD_cors &lt;-<span class="st"> </span>FC_scores_together <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(pheno, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;dataset&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(DX <span class="op">==</span><span class="st"> &quot;SSD&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subject, dataset, edge_group, wFC_score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(edge_group, wFC_score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>subject, <span class="op">-</span>dataset) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">cor</span>(.) 

<span class="kw">heatmap</span>(<span class="kw">abs</span>(SSD_cors))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">HC_cors &lt;-<span class="st"> </span>FC_scores_together <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">inner_join</span>(pheno, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;dataset&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(DX <span class="op">==</span><span class="st"> &quot;CTRL&quot;</span>, vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(subject, dataset, edge_group, wFC_score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(edge_group, wFC_score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>subject, <span class="op">-</span>dataset) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">cor</span>(.) 

<span class="kw">heatmap</span>(<span class="kw">abs</span>(HC_cors))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Marginal densities along x axis</span>
plot_DX_scatter_elipsed &lt;-<span class="st"> </span><span class="cf">function</span>(df, x, y) {
  <span class="co">#the tidy eval ness</span>
  xvar &lt;-<span class="st"> </span><span class="kw">enquo</span>(x)
  yvar &lt;-<span class="st"> </span><span class="kw">enquo</span>(y)
  <span class="co"># make the main scatte bit using above</span>
  main_scatter &lt;-<span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">data =</span> df, 
               <span class="kw">aes</span>(<span class="dt">x =</span> <span class="op">!!</span>xvar, <span class="dt">y =</span> <span class="op">!!</span>yvar, <span class="dt">color =</span> DX)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.7</span>, <span class="dt">size =</span> <span class="fl">0.7</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_ellipse</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;grey20&quot;</span>,<span class="st">&quot;red&quot;</span>))

  xdens &lt;-<span class="st"> </span><span class="kw">axis_canvas</span>(main_scatter, <span class="dt">axis =</span> <span class="st">&quot;x&quot;</span>)<span class="op">+</span>
<span class="st">    </span><span class="kw">geom_density</span>(<span class="dt">data =</span> df, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="op">!!</span>xvar, <span class="dt">fill =</span> DX),
              <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">size =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;grey20&quot;</span>,<span class="st">&quot;red&quot;</span>))

  ydens &lt;-<span class="st"> </span><span class="kw">axis_canvas</span>(main_scatter, <span class="dt">axis =</span> <span class="st">&quot;y&quot;</span>, <span class="dt">coord_flip =</span> <span class="ot">TRUE</span>)<span class="op">+</span>
<span class="st">    </span><span class="kw">geom_density</span>(<span class="dt">data =</span> df, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="op">!!</span>yvar, <span class="dt">fill =</span> DX),
                <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">size =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;grey20&quot;</span>,<span class="st">&quot;red&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()
  
  <span class="co">#putting the peices together</span>
  p1 &lt;-<span class="st"> </span><span class="kw">insert_xaxis_grob</span>(main_scatter, xdens, grid<span class="op">::</span><span class="kw">unit</span>(.<span class="dv">2</span>, <span class="st">&quot;null&quot;</span>), <span class="dt">position =</span> <span class="st">&quot;top&quot;</span>)
  p2&lt;-<span class="st"> </span><span class="kw">insert_yaxis_grob</span>(p1, ydens, grid<span class="op">::</span><span class="kw">unit</span>(.<span class="dv">2</span>, <span class="st">&quot;null&quot;</span>), <span class="dt">position =</span> <span class="st">&quot;right&quot;</span>)
  <span class="kw">return</span>(p2)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(cowplot)
fplot &lt;-<span class="st"> </span>FC_scores_together <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(pheno, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;dataset&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(vertex_type <span class="op">==</span><span class="st"> &quot;pvertex&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unite</span>(directed_edge_group, effect_direction, edge_group) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unite</span>(dat_sub, dataset, subject) <span class="op">%&gt;%</span><span class="st">  </span>
<span class="st">  </span><span class="kw">select</span>(dat_sub, Site, DX, directed_edge_group, wFC_score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(directed_edge_group, wFC_score) </code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggdraw</span>(<span class="kw">plot_DX_scatter_elipsed</span>(fplot, <span class="dt">x =</span> hyper_subcort_to_VI, <span class="dt">y =</span> hypo_subcort_to_FP))</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-41-1.png" width="480" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggdraw</span>(<span class="kw">plot_DX_scatter_elipsed</span>(fplot, <span class="dt">x =</span> hyper_subcort_to_VI, <span class="dt">y =</span> hypo_cerebullum_to_striatum))</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-42-1.png" width="480" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggdraw</span>(<span class="kw">plot_DX_scatter_elipsed</span>(fplot, <span class="dt">x =</span> hyper_subcort_to_SM, <span class="dt">y =</span> hypo_subcort_to_FP))</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-43-1.png" width="480" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fig1 &lt;-<span class="st"> </span>fplot <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> hypo_subcort_to_FP, <span class="dt">x =</span> DX, <span class="dt">color =</span> DX)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">outlier.shape =</span> <span class="ot">NA</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">binaxis =</span> <span class="st">&#39;y&#39;</span>, <span class="dt">stackdir =</span> <span class="st">&#39;center&#39;</span>, <span class="dt">binwidth =</span> <span class="fl">0.01</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;grey20&quot;</span>,<span class="st">&quot;red&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>( <span class="op">~</span><span class="st"> </span>Site, <span class="dt">ncol =</span> <span class="dv">4</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="ot">NULL</span>)

<span class="co">#ggsave(fig1, filename = &#39;VA_results.png&#39;,height = 8, width = 5)</span>

fig1</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-44-1.png" width="576" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fig1 &lt;-<span class="st"> </span>fplot <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> hyper_subcort_to_SM, <span class="dt">x =</span> DX, <span class="dt">color =</span> DX)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">outlier.shape =</span> <span class="ot">NA</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">binaxis =</span> <span class="st">&#39;y&#39;</span>, <span class="dt">stackdir =</span> <span class="st">&#39;center&#39;</span>, <span class="dt">binwidth =</span> <span class="fl">0.01</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;grey20&quot;</span>,<span class="st">&quot;red&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>( <span class="op">~</span><span class="st"> </span>Site, <span class="dt">ncol =</span> <span class="dv">4</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="ot">NULL</span>)

<span class="co">#ggsave(fig1, filename = &#39;VA_results.png&#39;,height = 8, width = 5)</span>

fig1</code></pre></div>
<p><img src="06_whole_matrix_stats_files/figure-html/unnamed-chunk-45-1.png" width="576" /></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="whole-connectome-results.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="calculate-weighted-subject-scores-by-chopping-up-the-matrix.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/TIGRLab/SZ_PINT/edit/master/notebooks/Rmd/06_whole_matrix_stats.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["SSD_PINT_full.pdf"],
"toc": {
"collapse": "section"
},
"toolbar": {
"position": "fixed"
},
"search": true,
"share": {
"github": true
}
});
});
</script>

</body>

</html>
